### PR TITLE
[DOC] change n_dimensions to n_channels in all files

### LINKED ISSUE #564: [DOC] Purge `n_dimensions` in deep learners
### Describe the issue linked to the documentation

In all deep learners, there are still the `n_dimensions` in the docstrings being used. 

### Suggest a potential alternative/fix

It should be `n_channels` to be more homogeneous with all `aeon` modules.

### PR DESCRIPTION
**Pull request by xiaopu222**
#### Reference Issues/PRs

fixes #564

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Review by TonyBagnall — APPROVED** [review]
lgtm

**Review by MatthewMiddlehurst — APPROVED** [review]
good change, thanks.

**Comment by TonyBagnall** [comment]
@all-contributors please add @xiaopu222 for this PR contribution

**Comment by TonyBagnall** [comment]
@all-contributors please add @xiaopu222 for PR https://github.com/aeon-toolkit/aeon/pull/918

**Comment by TonyBagnall** [comment]
@all-contributors please add @xiaopu222 for documentation

**Pull request merged**
