### PR TITLE
[ENH] Switch SFA Transformer to use numpy

### PR DESCRIPTION
**Pull request by TonyBagnall**
small PR to remove the nested_univ wrapping around the SFA component. Removed a flag to transform output, removed auto output format, adjusted tests to not use pandas. 

Only question was this. 

TODO remove imag-part from dc-component component

I removed it because I dont know what it means. Did you want to leave it there @patrickzib ?

### CODE REVIEW

**Comment by patrickzib** [comment]
> # TODO remove imag-part from dc-component component

It is ok to remove it.

**Comment by TonyBagnall** [comment]
something weird going on with the forecasting notebook, did not mean to change it, somehow pycharm and precommit did something. The changes seem benign? Otherwise I will revert to old one

**Comment by TonyBagnall** [comment]
lol, switch fit -> _fit

need to look closer I think
image

**Comment by TonyBagnall** [comment]
I've worked out how to make this work with _fit model I think, just need to work out a test that uses internal private methods

**Review by patrickzib — COMMENTED** [review]
Looks good to me. 

Could you check, if removing SFA from the `ECLUDE_ESTIMATORS` works, given your changes?

```python
EXCLUDE_ESTIMATORS = [
    # SFA is non-compliant with any transformer interfaces, #2064
    "SFA",
]
```

https://github.com/aeon-toolkit/aeon/blob/602e1e9aeade8da8fc467b1cc72f5d08dc7925ea/aeon/tests/_config.py#L11

**Comment by TonyBagnall** [comment]
it still fails two tests in test_transformers which it cannot pass: they test output type, which isnt recognised,

**Review by patrickzib — APPROVED** [review]
Fine with me.

**Pull request merged**
