### PR TITLE
[BUG] Fixes `stratified_resample` so that it works with 3D numpy

### LINKED ISSUE #459: [BUG] stratified_resample only works with dataframes
### Describe the bug

the function
def stratified_resample(X_train, y_train, X_test, y_test, random_state):
only works with nested dataframes. It should work with both 2D and 3D numpy, retaining DataFrame capability for backward compatibility

### Steps/Code to reproduce the bug

```python
import numpy as np
from aeon.utils.sampling import stratified_resample
X1 = np.random.random((10,1,100))
y1 = np.array([0,0,0,0,0,1,1,1,1,1])
X2 = np.random.random((10,1,100))
y2 = np.array([0,0,0,0,0,1,1,1,1,1])
X3, y3, X4, y4 = stratified_resample(X1,y1,X2,y2,0)
```

### Expected results

should work for 2D, 3D and pd.DataFrames

### Actual results

```python-traceback
Traceback (most recent call last):
  File "C:\Code\tsml-eval\local\debug.py", line 8, in <module>
    X3, y3, X4, y4 = stratified_resample(X1,y1,X2,y2,0)
  File "C:\Code\dpx-data-analysis\venv\lib\site-packages\aeon\utils\sampling.py", line 37, in stratified_resample
    all_data = pd.concat([X_train, X_test])
  File "C:\Code\dpx-data-analysis\venv\lib\site-packages\pandas\core\reshape\concat.py", line 372, in concat
    op = _Concatenator(
  File "C:\Code\dpx-data-analysis\venv\lib\site-packages\pandas\core\reshape\concat.py", line 462, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid
```

### Versions

_No response_

### PR DESCRIPTION
**Pull request by GuiArcencio**
#### Reference Issues/PRs

Fixes #459.

#### What does this implement/fix? Explain your changes.

Makes the `stratified_resample` function work with 3D and 2D numpy arrays, and DataFrames for backwards compatibility.

#### What should a reviewer concentrate their feedback on?

I've remade the function so that it deals mostly with indexes. This makes the function agnostic (for the most part) to the underlying implementation of `X_train` and `X_test`.

It still, however, can't deal with lists of 2D arrays (such as unequal length datasets). I can easily add that if necessary.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
great, thanks @GuiArcencio . If you could add capability for list of np.ndarray that would be really helpful

**Comment by GuiArcencio** [comment]
done :)

**Comment by TonyBagnall** [comment]
any chance you could add tests? Maybe just input each type with 50/50 class distribution, check you get that back?

**Comment by GuiArcencio** [comment]
sure! I parametrized the test function with the three different types of input

**Review by TonyBagnall — APPROVED** [review]
fantastic, thanks for doing this so quickly!

**Pull request merged**
