### PR TITLE
[ENH] Gaussian Filter Transformer

### PR DESCRIPTION
**Pull request by Cyril-Meyer**
#### Reference Issues/PRs

Implement Gaussian filter asked in #1920 (which is now fully completed).

#### What does this implement/fix? Explain your changes.

Add a new transformation, named `GaussSeriesTransformer` which use [SciPy gaussian_filter1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter1d.html)

#### Does your contribution introduce a new dependency? If yes, which one?

No, but we add another SciPy usage.

#### Any other comments?

Code is based on previous work `DFTSeriesTransformer`. I don't think I've forgotten anything, but there may still be references to the DFT as I started by copying _dft.py and test_dft.py.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

### CODE REVIEW

**Comment by Cyril-Meyer** [comment]
| sigma | ordre=0 | order=1 | order=2 |
| :--: | :--: | :--: | :--: |
| 0.1 | Gauss_0 1_0 | Gauss_0 1_1 | Gauss_0 1_2 |
| 0.5 | Gauss_0 5_0 | Gauss_0 5_1 | Gauss_0 5_2 |
| 1 | Gauss_1_0 | Gauss_1_1 | Gauss_1_2 |
| 2 | Gauss_2_0 | Gauss_2_1 | Gauss_2_2 |
| 5 | Gauss_5_0 | Gauss_5_1 | Gauss_5_2 |
| 10 | Gauss_10_0 | Gauss_10_1 | Gauss_10_2 |

**Comment by TonyBagnall** [comment]
great, thanks. The fails are unrelated all will be fixed by #2249

**Review by TonyBagnall — APPROVED** [review]
great, thanks for doing these, it would be really nice to have a notebook including all these nice graphs you have drawn

**Comment by Cyril-Meyer** [comment]
> great, thanks for doing these, it would be really nice to have a notebook including all these nice graphs you have drawn

Yes, good idea.

**Comment by MatthewMiddlehurst** [comment]
@Cyril-Meyer is the scipy function doing the same as what is described in the paper? I'm not quite sure.

image

**Comment by MatthewMiddlehurst** [comment]
I'm sure its fine either way, just trying to wrap my head around it really

**Pull request merged**
