### PR TITLE
[ENH] switch paa tests to use numpy

### PR DESCRIPTION
**Pull request by TonyBagnall**
another small change, make the tests of PAA use numpy arrays instead of data frames

### CODE REVIEW

**Comment by patrickzib** [comment]
Looks good to me. But can you remove the forecasting notebook?

**Comment by TonyBagnall** [comment]
that bloody notebook is following me around! I'll replace it with the one from main

**Comment by TonyBagnall** [comment]
> Looks good to me. But can you remove the forecasting notebook?

@patrickzib so I deleted it, copied it from main and pushed it, but it is still showing changes. No idea

**Comment by GuzalBulatova** [comment]
> > Looks good to me. But can you remove the forecasting notebook?
> 
> @patrickzib so I deleted it, copied it from main and pushed it, but it is still showing changes. No idea
Looks like there are just a bunch of spaces removed, can a pre-hook be a culprit? Although why would it run on a notebook that was reverted, curious.

**Review by patrickzib — APPROVED** [review]
👍

**Pull request merged**
