### PR TITLE
[ENH] Add support for array-like and statistical inputs as arguments in fill_value of Padding Transformer

### PR DESCRIPTION
**Pull request by aadya940**
Completes #402

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, thanks for this. What will happen if the series are multivariate, so n_channels >1. Does this pad each channel with (e.g.) an average value over all channels? If so, it would be better to work out the statistic for each channel separately. So if, each ```n_cases``` series is shape ```(n_channels, n_timepoints)``, then you should pad with the channel mean value, not the mean over all channels. Esp relevant if not normalised. For example, if this is (X,Y,Z) motion data, then the mean over all (X,Y,Z) will be very different to the mean over each channel separately.

**Comment by aadya940** [comment]
@TonyBagnall Got your point. Will make the changes ASAP, Thanks. Does the part where `fill_value` is an `np.ndarray` look fine?

**Comment by aadya940** [comment]
@TonyBagnall I hope this is better now. Should we just cast the Numpy Array to the appropriate size in 2D when a 1D Numpy Array is passed or raise an exception as done in my code?

**Review by TonyBagnall — APPROVED** [review]
lgtm, thanks

**Pull request merged**
