### PR TITLE
[ENH] Adding LITEMV ability to LITE

### PR DESCRIPTION
**Pull request by hadifawaz1999**
Adding a bool parameter `use_litemv` to LITE network, LITE classifier and regressor as well as LITETime classifier and regressor, for using the specific multivariate version, [paper for LITE Multivariate](https://arxiv.org/abs/2409.02869)

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
I thought we agreed to separate models in the end? Maybe I am misremembering this, did we write down notes?

**Comment by hadifawaz1999** [comment]
> I thought we agreed to separate models in the end? Maybe I am misremembering this, did we write down notes?

maybe i miss understood, and that we wont separate them but instead add an option for it

**Comment by hadifawaz1999** [comment]
> I thought we agreed to separate models in the end? Maybe I am misremembering this, did we write down notes?

after the meeting i was actually convinced that making it an option is better.

**Comment by MatthewMiddlehurst** [comment]
Possible I am just mistaken. This seems fine to me if it is for you. I would double-check the online API that the description includes both

**Comment by hadifawaz1999** [comment]
> Possible I am just mistaken. This seems fine to me if it is for you. I would double-check the online API that the description includes both

how to check online api on a pr ? never tried it:p

**Comment by MatthewMiddlehurst** [comment]
click on details on the read the docs test. Just a link to the website generated for this PR

**Review by TonyBagnall — DISMISSED** [review]
looks good, but could you add tests for this and the other options
https://app.codecov.io/gh/aeon-toolkit/aeon/blob/main/aeon%2Fclassification%2Fdeep_learning%2F_lite_time.py

image

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
