### PR TITLE
[ENH] Add minibatch param in MLPClassifier

### LINKED ISSUE #395: [ENH] ResNet and MLP are missing the use_mini_batch_size parameter
### Describe the feature or idea you want to propose

When ResNet, MLP and FCN were proposed, they were proposed with a batch size formula, check [this line](https://github.com/aeon-toolkit/aeon/blob/285acfa4fb1114dc51a96d62f121462be896bc2d/aeon/classification/deep_learning/fcn.py#L206) in FCN. This should be added to ResNet and MLP.

### Describe your proposed solution

will add it myself

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aadya940**
Fix #395

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Resolved a conflict, we previously decided to move away from the file-based author list. Odd CI didnt run on this before but seems to be fine now.

**Review by MatthewMiddlehurst — DISMISSED** [review]

**Comment by MatthewMiddlehurst** [comment]
LGTM, looks correct @hadifawaz1999 ?

**Review by hadifawaz1999 — CHANGES_REQUESTED** [review]
Thanks for this, just missing the addition of the parameter in the docstring

**Comment by hadifawaz1999** [comment]
> LGTM, looks correct @hadifawaz1999 ?

yes looks good just missing the docstring information for the parameter

**Comment by MatthewMiddlehurst** [comment]
ah good catch, yeah needs to be added to the docstring 🙂

**Comment by aadya940** [comment]
Will do it ASAP. Thanks 😊

**Review by MatthewMiddlehurst — APPROVED** [review]
lgtm

**Review by hadifawaz1999 — APPROVED** [review]
lgtm

**Pull request merged**
