### PR TITLE
[DOC] added reference to docstring of MERLIN anomaly detection

### PR DESCRIPTION
**Pull request by adm-unl**
#### Reference Issues/PRs
Reference #1705 

#### What does this implement/fix? Explain your changes.

Adds reference to docstring for MERLIN anomaly detection

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi @adm-unl not sure why this is failing on pre-commit, something about your set up maybe @MatthewMiddlehurst any ideas?

**Comment by MatthewMiddlehurst** [comment]
Seems to be an issue with forks, see https://github.com/aeon-toolkit/aeon/pull/1704

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by TonyBagnall** [comment]
@all-contributors add @adm-unl for docs

**Comment by MatthewMiddlehurst** [comment]
@allcontributors add @adm-unl for docs

**Pull request merged**
