### PR TITLE
[ENH] Parameterise the cost function of `dtw` and `adtw` distance measures

### PR DESCRIPTION
**Pull request by itsdivya1309**
#### Reference Issues/PRs
Closes: #1874

#### What does this implement/fix? Explain your changes.
As we discussed on the slack, I've implemented the parameterised DTW and ADTW as private functions to be used in the upcoming Proximity Forest 2.0.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
maybe these can go in distance module as parameter to the original dtw based functions ? not saying in this PR as i know its only used for PF2 for now, but future perspective, what do you think @chrisholder  ? however we should have a discussion on how it can affect BA stuff (some math related stuff if we go into this as a general parameter)

**Comment by MatthewMiddlehurst** [comment]
FYI there were some large conversations regarding this in the core_devs and distances Slack channels. It is not really compatible with the way those functions are currently set up, best to take a look at there.

For now we will do it like this just to move things forward.

**Comment by MatthewMiddlehurst** [comment]
I assume these are the same functions as your previous changes, but just in a new fine @itsdivya1309? If so I dont really see any issue for now.

**Comment by itsdivya1309** [comment]
> I assume these are the same functions as your previous changes, but just in a new fine @itsdivya1309? If so I dont really see any issue for now.

Yes, that's right.

**Review by MatthewMiddlehurst — COMMENTED** [review]
I think it looks fine for now, but I would put it in the same file as PF 2.0 rather than its own.

**Comment by MatthewMiddlehurst** [comment]
replaced by #1978

**Pull request closed without merging**
