### PR TITLE
[ENH] Improve Pairwise-Visualizations in plot_scatter()

### PR DESCRIPTION
**Pull request by patrickzib**
This PR updates the visualizations in plot_scatter for creating pairwise comparison plots.

- Adds figsize parameter to tune the size of the plot
- Adds color_palette as a parameter to change colors.
- Fixes issues with too small fonts in axes labels

### CODE REVIEW

**Review by dguijo — COMMENTED** [review]
Thank you for your work, @patrickzib. 

I'm sure it improves the scatters, and simplifies the colour codes. I'll do some testing tomorrow morning. I had some issues with the tight_layout in some plots, but can't remember which one. 

btw, I'll use your branch to catch an error of the statistical tests. I'll do it tomorrow.

Thank you again for your work.

**Comment by dguijo** [comment]
Hello again, Patrick, 

This is the warning that the `fig.tight_layout()` gave to me:
```
/home/dguijo/aeon/aeon/benchmarking/results_plotting.py:451: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()
```

Do you get this warning as well?

I've included the code to return a warning if all values are the same.

**Review by TonyBagnall — APPROVED** [review]
LGTM

**Comment by patrickzib** [comment]
Sorry, a bit late with my comments. Thank you for your work! :) Tony saw the User Waning, too. Not sure, if it is a problem. If tight_layout was not set, the layout looked strange at some times, with fonts not visible at the axes, though.

**Pull request merged**
