### PR TITLE
[MNT,DOC] Remove `__author__` lines for `__maintainer__`

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Implements #1095. See issue for reasoning.

Big annoying PR that replaces `__author__` with blank `__maintainer__` lines.

### CODE REVIEW

**Comment by dguijo** [comment]
Hello Matt! Thank you for this PR, I also think it's very needed for organisation. 
However, I think that maybe, as an starting point we can keep the names included in `__author__`, at least from those files that have changed since the split. If the file hasn't changed, we can include an empty list. 

What do you think? 

Thank you again, Matt! Good work.

**Comment by MatthewMiddlehurst** [comment]
It is going to be difficult to determine what file has changed since to split, or how significant a change must be to change the list (since every files has changes most likely due to refactors etc.).

I think a clean slate is easier IMO, but open to suggestions. Showing you have worked on the project is easier (and probably shows more valuable information) through GitHub.

**Comment by dguijo** [comment]
I agree with you. I proposed including some names just not to have the blank page syndrome or the name of the same people in almost all files.

Either way is good IMO. 
Thanks!

**Review by baraline — COMMENTED** [review]
I agree with the comments of Matthew, if people want to show their contributions, GitHub history will do the trick. We will populate the names as we work through files in future PRs and thanks to it people will know who to contact for questions about specific files.

**Review by baraline — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
Will merge, probably some stragglers with the current PRs but can do them later.

Feel free to fill in files as you wish.

**Pull request merged**
