### PR TITLE
[BUG] Improve sweep.yaml comment trigger

### PR DESCRIPTION
**Pull request by wwzeng1**
#### What does this implement/fix? Explain your changes.

This improves the sweep.yaml comment.

#### Does your contribution introduce a new dependency? If yes, which one?

NA

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage)
bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG] or [GOV] indicating
whether the PR topic is related to enhancement, maintenance, documentation, bugs or
governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS)
to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by wwzeng1** [comment]
@all-contributors please add @wwzeng1 for engineering

**Comment by wwzeng1** [comment]
https://github.com/all-contributors please add @wwzeng1 for bug

**Comment by MatthewMiddlehurst** [comment]
@all-contributors please add @wwzeng1 for fixing a bug

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
I'm going to piggy-back off this to remove the test rule also actually, I think it is too lax as well and not every file needs one really.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
