### PR TITLE
[DOC] `aeon` mentoring/project webpage

### LINKED ISSUE #1072: [DOC] Add a documentation section for intern projects
### Describe the issue linked to the documentation

Add a section in the docs dedicated to GSoC project proposals. 

- Propose a base structure for project proposal
- Add potential projects for similarity search and shapelet transform

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by baraline**
#### Reference Issues/PRs
Fixes #1072 

#### What does this implement/fix? Explain your changes.

Add a documentation page for GSoC projects.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi @baraline jumped in here and added a segmentation project, hope thats ok, I will add some more

**Comment by MatthewMiddlehurst** [comment]
do you mind if i edit this also? I would put it on the sidebar.

**Comment by hadifawaz1999** [comment]
am hoping on the branch to add some stuff

**Comment by MatthewMiddlehurst** [comment]
Reformatted a bit a fixed the links. Should be available from the sidebar now.

Not touched the project ideas other than the sections, will have a think about some.

**Comment by MatthewMiddlehurst** [comment]
This is the link to the page itself, be sure to check when it compiles after you make changes.

https://aeon-toolkit--1085.org.readthedocs.build/en/1085/mentoring.html

**Review by TonyBagnall — APPROVED** [review]
Maybe put this in and update on later PRs?

**Review by hadifawaz1999 — APPROVED** [review]
all good for getting this in now, we can see later if we add more stuff (to see for clustering cz we have a PR for resnet @TonyBagnall )

**Pull request merged**
