### PR TITLE
[ENH] Discrete Fourier Approximation Transformer

### PR DESCRIPTION
**Pull request by Cyril-Meyer**
#### Reference Issues/PRs

Implement DFT asked in #1920.

#### What does this implement/fix? Explain your changes.

Add a new transformation, named `DFTSeriesTransformer`.
The simplified algorithm is the following : 
1. Compute FFT
2. Remove a proportion of terms (r paramter)
3. Compute invert FFT

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### Any other comments?

Removed terms can be sorted by amplitude before removal to keep most important terms instead of first ones.

I based my code using `BKFilter` class as a template.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
-> I will use the bot when the PR is considered as ok.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

### CODE REVIEW

**Comment by Cyril-Meyer** [comment]
Here is a visualization of `x12r` vs `fit_transform(x12r)` with the tests parameters.
This looks good to me, but I may have misunderstood what is requested in #1920.

| r | Unsorted | Sorted |
| :--: | :--: | :--: |
| 0.00 | 0 0_False | 0 0_True |
| 0.25 | 0 25_False | 0 25_True |
| 0.50 | 0 5_False | 0 5_True |
| 0.75 | 0 75_False | 0 75_True |
| 1.00 | 1 0_False | 1 0_True |

**Comment by Cyril-Meyer** [comment]
@TonyBagnall I would like to mention you and ask for your opinion as you are the "feature requester".

**Review by TonyBagnall — APPROVED** [review]
lgtm, thanks

**Comment by Cyril-Meyer** [comment]
@all-contributors add @Cyril-Meyer for code.

**Review by hadifawaz1999 — APPROVED** [review]

**Pull request merged**
