### PR TITLE
[ENH] REDCOMETS tweaks / fixes

### PR DESCRIPTION
**Pull request by zy18811**
### What does this implement/fix? Explain your changes.

Several small tweaks / fixes to REDCOMETS, improving performance. 

image

### CODE REVIEW

**Review by MatthewMiddlehurst — APPROVED** [review]
LGTM, but need the current test results used for comparison updated. This is all in `testing/`.

If you need some help with this, let me know, I can get around to it eventually if you are busy.

**Comment by zy18811** [comment]
> LGTM, but need the current test results used for comparison updated. This is all in `testing/`.
> 
> If you need some help with this, let me know, I can get around to it eventually if you are busy.

Last commit should've now done this, please have a look and double check  :)

**Review by TonyBagnall — APPROVED** [review]
lgtm,. thanks

**Comment by patrickzib** [comment]
Not blocking, but would be nice to convert it to SFA_FAST at some point, which is much faster.

**Comment by TonyBagnall** [comment]
> Not blocking, but would be nice to convert it to SFA_FAST at some point, which is much faster.

maybe make an issue, same as with TDE?

**Comment by zy18811** [comment]
> Not blocking, but would be nice to convert it to SFA_FAST at some point, which is much faster.

Yeah, I did briefly look into doing this but ran into some numba weirdness so put it on the back burner for now. 

I’ll make an issue like @TonyBagnall suggested.

**Comment by patrickzib** [comment]
@zy18811 if you need help with SFA_FAST in the future, drop me a message.

**Pull request merged**
