### PR TITLE
[DOC] Update landing page

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
- Updates the landing page using the `furo` sphinx theme.
- Adds some placeholder logos.
- replaces the previous introduction, mission statement and content with panels linking to each module and links to social media.
- replaces the reStructuredTex .rst file with the more common Markdown .md

### CODE REVIEW

**Review by TonyBagnall — APPROVED** [review]
I cant really tell what it looks like, but good to progress so others can comment

**Comment by MatthewMiddlehurst** [comment]
You can see by pressing details on the docs test. Don't think we should merge yet as it breaks at least one other page and would be good to get comments.

image

**Review by GuzalBulatova — DISMISSED** [review]
Wow this is so good! I think the images for the ml tasks are great addition: they're informative, and make the landing page look way easier on the eye. One thing I'd change is make the red colour a bit more muted, what do you think? Of course this can be done further and isn't a blocker.
What is failing (you mentioned in the previous comment) @MatthewMiddlehurst ? All looks fine on my side.

**Comment by MatthewMiddlehurst** [comment]
Currently, the Installation page fails due to the style change. I agree the fonts and colour contrast should be worked on. I think I changed them on my fork to be a bit better, will try to pull it over to this PR when the package rename has settled.

**Comment by MatthewMiddlehurst** [comment]
Maybe there is no rush to change every page immediately though, I can have a look through and change the obvious things in another PR.

**Comment by lmmentel** [comment]
Looks great, let's merge this and start improving from there!

**Review by lmmentel — APPROVED** [review]
:+1:

**Review by lmmentel — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
No one seems to be against this, and we can change as we go. Of course, feel free to recommend updates whenever.

**Pull request merged**
