### PR TITLE
[MNT] Add runtime list for notebook test

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Records the runtime of notebooks in the notebook test workflow and prints it out at the end. i.e. 
`205	examples/networks/deep_learning.ipynb` 
which shows runtime (seconds) and then the notebook which was run.

Should help with #59, as people should be able to tell how long each notebook is taking now.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
this is what the output looks like (not the full list)

image

**Review by TonyBagnall — APPROVED** [review]
really useful!

**Comment by TonyBagnall** [comment]
dont think you wanted the print?

image

**Comment by MatthewMiddlehurst** [comment]
it outputs the actual command being run as well for other stuff, not sure that can be prevented

**Pull request merged**
