### PR TITLE
[DOC] Typo correction in getting started guide

### PR DESCRIPTION
**Pull request by IRKnyazev**
#### Reference Issues/PRs
Fixes #11841.

#### Does your contribution introduce a new dependency? If yes, which one?
No additional dependencies.

#### Any other comments?
The decision for removing the redundant 'n_timepoints'  was supported by Antoine.

### CODE REVIEW

**Comment by baraline** [comment]
Hey ! Thanks for contributing, I think there is a confusion on the `n_timepoint` thing. We never used `m_timepoint`, the second occurence might be a relicate of the time where we also use `n_timestamps`. The double occurrence of `n_timepoint` here is must be due to a mass replace of `n_timestamps` by `n_timepoints` and can be deleted

**Comment by IRKnyazev** [comment]
Hi @baraline,
thanks for the feedback, I will remove the second occurrence!

**Review by MatthewMiddlehurst — APPROVED** [review]
LGTM after the changes

**Comment by MatthewMiddlehurst** [comment]
It is good to fill out the initial PR as best you can. You can delete template bits if they do not apply. Good practice to link to issue if you can, i.e. "Fixes #1841" which will close that issue on merge.

**Pull request merged**
