### PR TITLE
set random_state in rotation forest

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs
see #711 

#### What does this implement/fix? Explain your changes.

attempts to fix the sporadic fail by setting the random_state in RotationForestClassifier

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
`_clone_estimator` should already be setting the random state, if it was not, I think we would be seeing issues with other estimators.

Have you managed to reproduce the failure locally? Just wondering if it is OS specific really.

**Comment by MatthewMiddlehurst** [comment]
Ah never mind, I see you have linked in the issue. Appears everywhere.

**Comment by TonyBagnall** [comment]
just had a quick scan and took a punt on this, its appearing frequently, but not so frequently to be an obvious bug. Cant reproduce it, although a lot of the fails are windows. Ah this fails for something else!

**Comment by MatthewMiddlehurst** [comment]
I think the test is just the transform portion, not the classifier

**Comment by TonyBagnall** [comment]
just ran it 20 odd times locally, no fails

**Pull request closed without merging**
