### PR TITLE
[DOC] Shapelet classifier notebook extensions & minor docstring corrections

### PR DESCRIPTION
**Pull request by IRKnyazev**
#### Reference Issues/PRs
I did not make an issue for this since these are just small improvements made while studying the algorithms.

#### What does this implement/fix? Explain your changes.
Made minor docstring corrections for example grammatical errors or typos. Then also tried to clarify any unclear aspects of the shapelet classifier notebook.

### CODE REVIEW

**Comment by IRKnyazev** [comment]
@baraline Could you please have a look through to check that you are happy with any explanations I have attempted to add.

**Review by baraline — DISMISSED** [review]
LGTM, thanks for the typos seems i left a lot of them !

**Comment by IRKnyazev** [comment]
Seems that for the original PR some pre-commit problems snuck through, I have corrected them so this should be ready to be merged!

**Review by baraline — APPROVED** [review]
LGTM ! Thanks again :)

**Pull request merged**
