### PR TITLE
[DOC] Fixing `random_state` in docstrings

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
fixes: #1349 
adds a general docstring for `random_state`

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
I think there was a miss understanding, the idea is not to use the same documentation we used in #1271 , the idea is to check if there is somewhere where the documentation needs more information. For example in the case of deep learning it needed to be clarified about the GPU CPU thing in #1271  but thats not the case everywhere

**Comment by AnonymousCodes911** [comment]
> I think there was a miss understanding, the idea is not to use the same documentation we used in #1271 , the idea is to check if there is somewhere where the documentation needs more information. For example in the case of deep learning it needed to be clarified about the GPU CPU thing in #1271 but thats not the case everywhere

Understood!, will update according to the individual models! also, I think @MatthewMiddlehurst  has given general docstrings to some, should I follow the same suite and add specifics to the modules which need them? 

general docstrings: 
```
    random_state : int, RandomState instance or None, default=None
        If `int`, random_state is the seed used by the random number generator;
        If `RandomState` instance, random_state is the random number generator;
        If `None`, the random number generator is the `RandomState` instance used
        by `np.random`.
```

**Comment by hadifawaz1999** [comment]
> > I think there was a miss understanding, the idea is not to use the same documentation we used in #1271 , the idea is to check if there is somewhere where the documentation needs more information. For example in the case of deep learning it needed to be clarified about the GPU CPU thing in #1271 but thats not the case everywhere
> 
> Understood!, will update according to the individual models! also, I think @MatthewMiddlehurst has given general docstrings to some, should I follow the same suite and add specifics to the modules which need them?
> 
> general docstrings:
> 
> ```
>     random_state : int, RandomState instance or None, default=None
>         If `int`, random_state is the seed used by the random number generator;
>         If `RandomState` instance, random_state is the random number generator;
>         If `None`, the random number generator is the `RandomState` instance used
>         by `np.random`.
> ```

yeah i think this part should be the same everywhere (if the code does that, if not than not) correct me if am wrong @MatthewMiddlehurst

**Comment by MatthewMiddlehurst** [comment]
Be careful, this may not be appropriate for every `random_state`. Generally if it goes through `check_random_state` it should be fine.

**Comment by AnonymousCodes911** [comment]
will be done in #1417

**Pull request closed without merging**
