### PR TITLE
[ENH] TimeSeriesKMeans init_algorithm

### PR DESCRIPTION
**Pull request by Sharathchenna**
#2036 
 
What does this implement/fix? Explain your changes.
This change renames the init_algorithm argument in the aeon KMeans implementation to init, aligning it with the naming convention used in scikit-learn

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
thanks for doing this, normally we would need this to be deprecated. This means keeping the old and new variables, default the old one to deprecated, then if it is set in the constructor, issue a warning and set init to the value passed. Think this is correct @MatthewMiddlehurst ? Is there a current example?

**Comment by Sharathchenna** [comment]
@TonyBagnall Made the changes. Please tell me if I need to do anything else.

**Comment by TonyBagnall** [comment]
@all-contributors add @Sharathchenna for code

**Review by TonyBagnall — APPROVED** [review]
LGTM, thanks

**Pull request merged**
