### PR TITLE
[ENH] Updated regression/deeplearning.

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
#### Reference Issues/PRs 
Fixes: #1218
Refer: #1198 

#### What does this implement/fix? Explain your changes.
 - made a new file _mlp.py
 - initialized MLPRegressor in __init__.py file
 
This is done in order to adapt the various instances from deep learning -classifier to regression.
Furthermore, I need guidance to ensure that I am following the correct path so i can push the upcoming commits!

#### Does your contribution introduce a new dependency? If yes, which one?
None

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Hi, we talked in slack on refocusing this on to MLP rather than both, but #1214 has also made PR for MLP so maybe we should go for encoder instead. Feel free to ask questions if you are stuck. `FCNClassifier` and `FCNRegressor` are good examples of a classification deep learned ported over to regression.

**Comment by aadya940** [comment]
Hey @MatthewMiddlehurst , Since @AnonymousCodes911 is working on `EncoderRegressor` now. Can I start working on `LITETimeClassifier` ?

**Comment by hadifawaz1999** [comment]
> Hey @MatthewMiddlehurst , Since @AnonymousCodes911 is working on `EncoderRegressor` now. Can I start working on `LITETimeClassifier` ?

yes of course ! both LITETimeRegressor and IndividualLITERegressor will be in the same file, as for LITETimeClassifier and IndividualLITEClassifier

**Comment by AnonymousCodes911** [comment]
@hadifawaz1999, please review if the changes are in line, please ignore the indentation.

**Comment by MatthewMiddlehurst** [comment]
I would have a try uncommenting and finishing off the regressor, it will be easier to provide feedback from there.

**Comment by AnonymousCodes911** [comment]
@MatthewMiddlehurst I was facing flake8-> W293 error, none of the fixes worked for me, hence had to bypass pre-commit, can you help me in handling that error?

**Comment by AnonymousCodes911** [comment]
> > Hey @MatthewMiddlehurst , Since @AnonymousCodes911 is working on `EncoderRegressor` now. Can I start working on `LITETimeClassifier` ?
> 
> yes of course ! both LITETimeRegressor and IndividualLITERegressor will be in the same file, as for LITETimeClassifier and IndividualLITEClassifier

@aadya940, _lite_time.py is a relatively large(?) file to adapt would you like to split the work?

**Comment by MatthewMiddlehurst** [comment]
Usually if the dev install is used and pre-commit is running this is automatically fixed. As long as there is a newline at the end of the file the error should not be appearing. I'm not sure what your local setup is like, but try manually adding the newlines at the end of the file.

**Comment by AnonymousCodes911** [comment]
> Usually if the dev install is used and pre-commit is running this is automatically fixed. As long as there is a newline at the end of the file the error should not be appearing. I'm not sure what your local setup is like, but try manually adding the newlines at the end of the file.

Thankyou, I 'll try that

**Comment by MatthewMiddlehurst** [comment]
Replaced by #1226

**Pull request closed without merging**
