### PR TITLE
[DEP] Remove shapeDTW

### PR DESCRIPTION
**Pull request by TonyBagnall**
Removes the shapeDTW classifier as part of #1239. Apparently its logically incorrect, see #788 @hadifawaz1999

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
yes am working now on a new implementation that is correct and more clear, should be ready soon @TonyBagnall

**Comment by hadifawaz1999** [comment]
i think it should be removed from the notebooks as well

**Review by MatthewMiddlehurst — COMMENTED** [review]
Is this still in the API? Probably should have asked that for the other deprecations 🙂

**Comment by TonyBagnall** [comment]
> Is this still in the API? Probably should have asked that for the other deprecations 🙂

good point, I will check them all on this PR

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
