### PR TITLE
[ENH] Introducing visualisation module

### LINKED ISSUE #794: [ENH] Where to locate plotting functionality?
### Describe the feature or idea you want to propose

during #782 I came across series plotting utils in annotation. We have other plotting functionality for both series and results in various locations. I think it could be tidied up. 

any thoughts?

### Describe your proposed solution

Possible solutions
1. Move all plotting to utils.
2. Move all to benchmarking
3. Introduce a visualisation module, where the results plotting (benchmarking) and series plotting (annotation and utils)

feel free to add more.

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TonyBagnall**
Fixes #794 
See #140 #451 #592 

this centralises the plotting functionality  from annotation, benchmarking, clustering and utils into a new module, visualisation. 

I've called it visualisation rather than plotting because we can include other tools for explainability such as feature relevance, but dont mind if its plotting instead. 

Still to do is to centralise the examples, sort out naming for plot series and standardise the function signatures and naming

### CODE REVIEW

**Review by dguijo — COMMENTED** [review]
Thank you for your work, Tony!

I think is a good idea to unify all plotting stuff in one module with different sub-modules depending on the functionality. 

I have a question regarding methods. Do all these plot_ functions return the same matplotlib object? or just plot whatever and do not return anything. 
I think we should keep the same practice for all these functions, and in my opinion just return the plot without plotting anything (if so, maybe the function names should replace "plot" by "create" or other more appropriate word, which I leave for native people :))

Thank you again, good work!

**Comment by TonyBagnall** [comment]
> Thank you for your work, Tony!
> 
> I think is a good idea to unify all plotting stuff in one module with different sub-modules depending on the functionality.
> 
> I have a question regarding methods. Do all these plot_ functions return the same matplotlib object? or just plot whatever and do not return anything. I think we should keep the same practice for all these functions, and in my opinion just return the plot without plotting anything (if so, maybe the function names should replace "plot" by "create" or other more appropriate word, which I leave for native people :))
> 
> Thank you again, good work!

hi David, I dont really know tbh, just want to get it all in one place then we can look more closely at how they work

**Review by dguijo — DISMISSED** [review]
LGTM. Good work, Tony. We leave the decision about how to organise plot functions for the next PR :)

**Review by dguijo — APPROVED** [review]
LGTM, Thanks Tony!

**Pull request merged**
