### PR TITLE
[DOC] Move forecasting notebooks

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs
part of https://github.com/aeon-toolkit/aeon/issues/507

#### What does this implement/fix? Explain your changes.

moves forecasting notebooks into their own dir, renames them to remove bizarre prefixes and adds an image for proabilistic. No content changed at all

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
May be other concerns by @ltsaprounis and @aiwalter, but i think the only potential issue with this move is that I cant see any change to the usage of the `glocal_fc` folder and some of the images. Either they are unused or the path to use them has not been updated.

**Comment by MatthewMiddlehurst** [comment]
How did Markus get pinged as a code owner 🤔

**Comment by TonyBagnall** [comment]
> How did Markus get pinged as a code owner 🤔

codeowners I guess, will give it a tidy up soon

**Review by MatthewMiddlehurst — APPROVED** [review]
The only issue I can see is that the change broke the links in the user guide page (the datasets one seems broken also). Will approve but would be good to fix those even if the page is still to be updated.

**Comment by TonyBagnall** [comment]
I'd not looked at the user guide at all, will update it now

**Pull request merged**
