### PR TITLE
[ENH] MrSEQLClassifier wrapper

### LINKED ISSUE #1738: [ENH] Categorisation of MrSQM and MrSEQL algorithms
### Describe the issue

MrSQM and MrSEQL are  currently categorised under TSC shapelet methods. We think the categorisation  should change to dictionary_methods. We don't think of them as shapelet methods, because they are more similar to dictionary-methods of the WEASEL type, than shapelet methods in how they work, e.g. there is no distance involved in the MrSQM/MrSEQL algorithms as in shapelet methods.

Both algos can be easily installed with pip:
pip install mrseql
pip install mrsqm

MrSQM can also be used as a transformer to extract features, see here:
https://github.com/mlgig/mrsqm/blob/main/example/Time_Series_Classification_and_Explanation_with_MrSQM.ipynb

### Suggest a potential alternative/fix

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Fixes #1738

#### What does this implement/fix? Explain your changes.

Start of a `mrseql` wrapper. Unfortunately, I can't quite find how to parameterise it currently after installing on Windows 🙂.

If anyone can find it in the source that that would be helpful: https://github.com/lnthach/Mr-SEQL

#### Does your contribution introduce a new dependency? If yes, which one?

`mrseql`

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
@lnthach Hi Thach, I am having a bit of trouble figuring out what parameters your MrSEQL pypi package has and what defaults I should set for them. Would you be able to comment and help me with this?

**Comment by lnthach** [comment]
@MatthewMiddlehurst Hi Matthew, I just updated mrseql (v0.0.4) on pypi so I hope it would make things easier for you. I also remove sktime dependency but use fftw3 library instead (same dependencies as mrsqm).

Currently there are three parameters for MrSEQLClassifier and the default values are as follows:
`
MrSEQLClassifier(seql_mode='fs', symrep=('sax'), custom_config=None)`

Please let me know if it works for you.

**Comment by MatthewMiddlehurst** [comment]
@lnthach Thanks for this. Raised the version found but it seems to be failing to install on our Linux runner (https://github.com/aeon-toolkit/aeon/actions/runs/10247769782/job/28347641403?pr=1756). mrsqm installs fine by the look of things

**Comment by lnthach** [comment]
@MatthewMiddlehurst This one is strange. Both uses the same sfa implementation so both depends on fftw3. One possible reason is that mrsqm installed from built distribution hence the installation somehow bypassed this dependency (not sure if this is possible to be honest). I have some issues with generating the built distribution for mrseql so I uploaded only the source distribution. Do you think this could be the reason ?

**Comment by MatthewMiddlehurst** [comment]
@lnthach I think thats likely, not really sure how to resolve it through as I dont have much experience wrapping C, let alone distributing it 🙂. If the parameters used are the same I can restrict it to 0.0.2 for now?

**Comment by lnthach** [comment]
@MatthewMiddlehurst I just uploaded the built distribution for v0.0.4. Could please you check if it still fails ?

**Comment by MatthewMiddlehurst** [comment]
Seems to all be running fine @lnthach

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
