### PR TITLE
[ENH] Function to write to Monash tsf style

### LINKED ISSUE #469: [ENH] Function to write to Monash tsf style
### Describe the feature or idea you want to propose

we have a function that can load forecasting data in tsf format used by https://forecastingdata.org/. It would be good to have the ability to save files into the same format

### Describe your proposed solution

function along the lines of write_to_tsfile in the datasets module, _data_loaders.py

### PR DESCRIPTION
**Pull request by itsdivya1309**
#### Reference Issues/PRs
Fixes #469 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Thanks for contributing. I'll leave this since it's a draft, but feel free to ask any questions/for a review.

**Comment by itsdivya1309** [comment]
Sure, will reach out to you for review once it's done.

**Review by MatthewMiddlehurst — APPROVED** [review]
Yep fine with this being expanded on in future PRs. Agree with Tonys comments.

**Comment by TonyBagnall** [comment]
@all-contributors add @itsdivya1309 for datasets

**Pull request merged**
