### PR TITLE
[BUG] `attrs` quick fix

### LINKED ISSUE #282: [BUG] `attrs` dependency discussion
The `attrs` dependency is no longer being installed on CI, we should add it as an actual dependency or remove its usage.
It is currently only used in 2 annotation estimators (GGS and IGTS) which I believe were developed by @lmmentel.

----

Issue for discussion of `attrs` as a dependency.

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Not sure if this will work, but crudely removes any imports for the `attrs` module.
Related #282.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
There is probably a better way to handle this, I am not familiar with the removed package or its usage in these classes. Probably best for @lmmentel to suggest the best course.

**Comment by MatthewMiddlehurst** [comment]
The codecov checks are back... yay, I guess?

**Comment by lmmentel** [comment]
I would be for taking attrs as a dependency instead of removing the use.

**Comment by MatthewMiddlehurst** [comment]
Ok, I have just added it as a soft dependency for now. Think it is worth discussion in the issue though.

**Comment by MatthewMiddlehurst** [comment]
never mind, it was failing the soft-dep test anyway! would have to be an actual dependency.

**Review by TonyBagnall — APPROVED** [review]
so I guess we have this as a hard dep for now, but I cant really see the benefit it gives myself.

**Review by lmmentel — APPROVED** [review]

**Comment by lmmentel** [comment]
Thanks for putting it in @MatthewMiddlehurst! 

@TonyBagnall this was an experiment in a bit more modern definition of estimator classes. [attrs](https://www.attrs.org/en/stable/index.html) has a pretty good docs where they explain what it is good for if you're interested.

I'm all for having a discussion whether it fits the overall design we're going for. I'm happy to make an argument for it but in the context of multiple inheritance madness we have now it shouldn't be that hard of a sell.

**Pull request merged**
