### PR TITLE
[ENH] fixed sqr error

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
#### Reference Issues/PRs
fixes: #1234 

#### What does this implement/fix? Explain your changes.
we do not need to calculate the square.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [x] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
holding this off for now till we discuss about it in a couple of weeks

**Comment by TonyBagnall** [comment]
I think we could put this in, as you said @hadifawaz1999 it is currently incorrect. what do you think?

**Comment by hadifawaz1999** [comment]
> I think we could put this in, as you said @hadifawaz1999 it is currently incorrect. what do you think?

i prefer if we dig deeper and see if its even done elsewhere, because i think it is given it does  not only affect the KNN classifier

**Review by hadifawaz1999 — APPROVED** [review]
LGTM for now, we should keep this in mind and search other places it has been assuming the square rooting thing

**Review by chrisholder — DISMISSED** [review]

**Comment by AnonymousCodes911** [comment]
@hadifawaz1999, after changing : 
```python
        if self.weights == "distance":
            ws = distances[closest_idx]
            ws = ws**2 # removing this

            # Using epsilon ~= 0 to avoid division by zero
```

the output changed drastically : 
Actual predictions: [-144.41037008  -25.55876587 -229.9764678 ]
Expected predictions: [-216.06541863   -4.54133078 -324.7624233 ]

how should we tackle this?

**Review by hadifawaz1999 — APPROVED** [review]

**Pull request merged**
