### PR TITLE
[MNT] Distance module refactor part 2

### PR DESCRIPTION
**Pull request by chrisholder**
#### Reference Issues/PRs
#2161 #2170 

#### What does this implement/fix? Explain your changes.
This PR is part 2 of cleaning up this distance module. This PR focuses on moving the remaining distances to an appropriate directory and cleaning up the code now that pairwise_distance is no longer a numba function (can use kwargs).

#### Any other comments?
Some tests are disabled for the min distances and their coverage is lower than the others. This will be addressed in the distance module cleanup part 3.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [x] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Is this still relevant? https://github.com/aeon-toolkit/aeon/pull/2170/files#diff-01a85f7ce36af292445124118eeab7646bc1de533efe47b579a7c2d67280df73R379

**Review by baraline — COMMENTED** [review]
Lgtm, new structure makes it alot cleaner and removes these long list of if else. Nice job ! Not approving yet as I can't view Matthew's link from phone.

**Comment by chrisholder** [comment]
> Is this still relevant? https://github.com/aeon-toolkit/aeon/pull/2170/files#diff-01a85f7ce36af292445124118eeab7646bc1de533efe47b579a7c2d67280df73R379

Removed - it was a leftover note to self to test it (which it now has been)!

**Review by TonyBagnall — APPROVED** [review]
LGTM

**Comment by chrisholder** [comment]
This PR will break everything unless the numba cache's are update so will merge close to midnight

**Pull request merged**
