### PR TITLE
[MNT] Update `ElasticEnsemble` test to work with all distances

### LINKED ISSUE #1499: [MNT] Test `ElasticEnsemble` with all distances
### Describe the issue

The EE classifier does not test with all distances according to the [coverage stats](https://app.codecov.io/gh/aeon-toolkit/aeon/blob/main/aeon%2Fclassification%2Fdistance_based%2F_elastic_ensemble.py#L141).

### Suggest a potential alternative/fix

Write a test in `test_elastic_ensemble.py` which ensures this works correctly. Other parameters can be tweaked to speed up the test if  necessary and it does not compromise the test output.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by itsdivya1309**
#### Reference Issues/PRs
Tries to fix #1499 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by itsdivya1309** [comment]
@MatthewMiddlehurst, does this fix the issue?

**Comment by baraline** [comment]
Hey @itsdivya1309 changes looks good to me, just need to test coverage again to see if the issue is solved. Changing tags accordingly.

**Comment by MatthewMiddlehurst** [comment]
Hi, not quite what I was going for, I could have explained it better 🙂. The distances used in EE should only be the ones from the paper, so unless those were missing and should be there we dont want to include them.

What I wanted was for a `pytest` test to be added which tests the `"all"` options of the distance parameter. If you click on the coverage report in the issue, this is not currently tested.

**Comment by itsdivya1309** [comment]
> Hi, not quite what I was going for, I could have explained it better 🙂. Odd that those are excluded though, not sure why. Maybe they weren't used in the original paper?
> 
> What I wanted was for a `pytest` test to be added which tests the `"all"` options of the distance parameter. If you click on the coverage report in the issue, this is not currently tested.

Hi!
The distances were in the `ElasticEnsemble` class, but not here, so I added them. I still need to check the paper, though.

I have added a test. Would this work?

**Review by MatthewMiddlehurst — APPROVED** [review]
LGTM!

**Pull request merged**
