### PR TITLE
[ENH]Efficiency slope transformer

### LINKED ISSUE #249: [ENH] Improve the efficiency of SlopeTransformer
**Is your feature request related to a problem? Please describe.**
the SlopeTransformer in transformations/panel/slope.py has been converted to use numpy arrays rather than data frames internally in PR #250 . However, it still relies on a lot of looping and lists, which I'm sure is inefficient. It could be done much faster with numpy operations.

**Describe the solution you'd like**
I would like a timing experiment with current code, reworking using numpy ops, then a timing test after the refactor to show speed up. 

**Describe alternatives you've considered**
Leave it as is. It is used in ShapeDTW, but nowhere else. This is a good first issue for someone wanting to get involved in algorithm development, but it is hardly pressing.

### PR DESCRIPTION
**Pull request by steenrotsman**
#### Reference Issues/PRs

Fixes #249.

#### What does this implement/fix? Explain your changes.
Goal was to do more heavy lifting in numpy to improve code efficiency.

```
from time import perf_counter
from itertools import product
for length, intervals in product([100], [2, 10, 25]):
    X = np.random.randint(0, 100, (100, 100, length))
    start = perf_counter()
    s = SlopeTransformer(n_intervals=intervals).fit(X)
    res = s.transform(X)
    end = perf_counter()
    print(f'{length},{intervals},{end-start}')
```

gives

length,intervals,new duration,old duration,old/new
100,2,0.45,2.51,5.58
100,10,2.12,4.23,1.99
100,25,5.32,7.37,1.38
1000,2,0.53,21.7,40.8
1000,10,2.24,23.7,10.5
1000,25,5.51,26.8,4.87

Significant speedup, which increases in time series length and interval size.
During editing, I (my IDE) noticed some docstrings that were too wide and a duplicated method.

#### What should a reviewer concentrate their feedback on?
* Reproduce speedup results. 
* Third commit in this branch is a bit out of scope.

#### Did you add any tests for the change?
No, the goal was to improve efficiency while keeping compliant with the existing tests.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
great, thanks for this. Matt and I are at a conference this week so will be a bit slow. The fail is not caused by you though, will look into it

**Comment by TonyBagnall** [comment]
bug independent of this pr for the examples fails, see #747,  will fix it soon

**Comment by TonyBagnall** [comment]
@steenrotsman could you update this from main? The notebook bug has been fixed

**Review by hadifawaz1999 — APPROVED** [review]
LGTM ! thanks for the work its definitely more efficient now

**Comment by TonyBagnall** [comment]
@steenrotsman thanks for the contribution. Could you add a small test function for _split if you get a chance?

**Pull request merged**
