### PR TITLE
[ENH] Convert remaining collection transformers

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Converts the remaining transformers in the `collection` sub package to use the new base class.

Returns the `PlateauFinder` class to collections for now.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
could you add the capability:multivariate tag to any you are converting that miss it at the moment?

**Comment by MatthewMiddlehurst** [comment]
I think that would be better in its own PR. We still have the duplicate tag which I want to deal with, will create an issue.

**Comment by TonyBagnall** [comment]
I think this has been subsumed by #825 and we can close this PR @MatthewMiddlehurst ?

**Comment by MatthewMiddlehurst** [comment]
I will take a look, I think there is a change to PlateuFinder I would like to revert.

**Pull request closed without merging**
