### PR TITLE
[MNT] Algorithm type Checking

### PR DESCRIPTION
**Pull request by aryanpola**
What does this implement/fix? Explain your changes.
Checking for valid algorithm types
#1952 

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

### CODE REVIEW

**Review by MatthewMiddlehurst — COMMENTED** [review]
Few thoughts:

1. This doesn't need a method, just a test IMO
2. I would have this as a test for all estimators, so in `testing/estimator_checking`
3. I wouldn't raise an error for missing tags currently

**Comment by MatthewMiddlehurst** [comment]
Also please do keep to the title naming structure and template as much as possible when creating PRs, it makes triage easier

**Comment by MatthewMiddlehurst** [comment]
I think there may be a misunderstanding here with how we test our estimators, please feel free to ask questions if the issue is confusing. The current code essentially tests a method which does not exist.

What we want to do is check if the `algorithm_type` tag for an estimator (checking all collection estimators i.e. classifiers, regressors and clusterers) is a valid entry.

**Comment by aryanpola** [comment]
> I think there may be a misunderstanding here with how we test our estimators, please feel free to ask questions if the issue is confusing. The current code essentially tests a method which does not exist.
> 
> What we want to do is check if the `algorithm_type` tag for an estimator (checking all collection estimators i.e. classifiers, regressors and clusterers) is a valid entry.

Shouldn't the code check if the input for tag `algorithm_type` is in the list of algorithm types?

**Comment by MatthewMiddlehurst** [comment]
Yes that would be the test.

**Comment by aryanpola** [comment]
> I think there may be a misunderstanding here with how we test our estimators, please feel free to ask questions if the issue is confusing. The current code essentially tests a method which does not exist.
> 
> What we want to do is check if the `algorithm_type` tag for an estimator (checking all collection estimators i.e. classifiers, regressors and clusterers) is a valid entry.

Would having a list of names of classifiers, regressors, and clusterers be fine?
Then, check if the algorithm type from the list is valid.

**Pull request closed without merging**
