### PR TITLE
un-exclude classifiers from tests

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs
See
https://github.com/sktime/sktime/issues/3103
See
https://github.com/aeon-toolkit/aeon/issues/420
#271 
#347 
#### What does this implement/fix? Explain your changes.

several classifiers were excluded from all tests due to sporadic failures. I was not active at the time and can no longer see the errors, so I will try to reproduce them here. 

I have also fixed a couple of things that were causing test failure. 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [ ] For new estimators, I've added the estimator to the online documentation.

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
you should keep [this](https://github.com/aeon-toolkit/aeon/pull/430/commits/fa1ee259d91a82eb4966264a061f794bb5907e46) in mind . It might be necessary to get #430 before this PR in order to avoid fails on deep learning. I decided to purge any reference of pickle in deep classifiers and regressors, it doesnt work so might as well removing it.

**Comment by TonyBagnall** [comment]
Going to run this 10 times 

> you should keep [this](https://github.com/aeon-toolkit/aeon/pull/430/commits/fa1ee259d91a82eb4966264a061f794bb5907e46) in mind . It might be necessary to get #430 before this PR in order to avoid fails on deep learning. I decided to purge any reference of pickle in deep classifiers and regressors, it doesnt work so might as well removing it.

the resnet exclusion was from a separate bug, so can do #430 independently of this.

**Comment by TonyBagnall** [comment]
Going to run this ten times see if it fails
1. Passed
2.

**Comment by TonyBagnall** [comment]
so it recreates an error at least, although its on catch22, which wasnt on the excluded list. Head scratcher
https://github.com/aeon-toolkit/aeon/actions/runs/4985784640/jobs/8957150667?pr=421

**Comment by TonyBagnall** [comment]
so run failed, but it seems unrelated to this PR, the Catch22Classifier is not changed at all and not used by any of the un-excluded classifiers (AFAIK). I'm going to keep rerunning it later, but other PRs are building so will wait 

..................................................................
=================================== FAILURES ===================================
_________________________ aeon/tests/test_softdeps.py __________________________
[gw1] darwin -- Python 3.10.11 /Users/runner/hostedtoolcache/Python/3.10.11/x64/bin/python
worker 'gw1' crashed while running 'aeon/tests/test_softdeps.py::test_est_fit_without_modulenotfound[Catch22Classifier]'

**Pull request closed without merging**
