### PR TITLE
[MNT] Fix RDST CI failure and slow down

### LINKED ISSUE #2071: [MNT] Similarity search and RDST test failures in CI
### Describe the issue

Similarity search and RDST are currently causing some errors in CI:

https://github.com/aeon-toolkit/aeon/actions/runs/10826946884/job/30039020141
https://github.com/aeon-toolkit/aeon/actions/runs/10863339134/job/30147372111
https://github.com/aeon-toolkit/aeon/actions/runs/10890837654/job/30220422286
https://github.com/aeon-toolkit/aeon/actions/runs/10910622966/job/30281472461
https://github.com/aeon-toolkit/aeon/actions/runs/10918273185/job/30303353216 (other failure here as well)
https://github.com/aeon-toolkit/aeon/actions/runs/10918965119/job/30305612433

In case these expire, here are some examples:

```
FAILED aeon/testing/tests/test_all_estimators.py::test_all_estimators[check_fit_updates_state(estimator=RDSTRegressor(max_shapelets=20),datatype=EqualLengthUnivariate-Regression-np-list)] - ReferenceError: underlying object has vanished
```

```
FAILED aeon/similarity_search/distance_profiles/tests/test_naive_distance.py::test_normalized_naive_distance[dtw-float64] - ReferenceError: underlying object has vanished
```

I don't see any failures in `numba` disabled tests, but there is a low sample size.

### Suggest a potential alternative/fix

Solve the case of the missing underlying object.

### Additional context

Tests on general CI disabled by #2080

### PR DESCRIPTION
**Pull request by baraline**
#### Reference Issues/PRs

Part1 to Fixes #2071  

#### What does this implement/fix? Explain your changes.

Remove distance argument from RDST, uniformize dtypes, use of strides (view of the original array), add new random generator API instead of old one.

Current results on this branch (original train test split) :
| Name                                   | Acc  | time  |
|-------------------|---|---|
| ACSF1|0.92|8.253568                                    |
| Adiac|0.7161125319693095|4.220171                      |
| AllGestureWiimoteX|0.7242857142857143|11.283452        | 
| AllGestureWiimoteY|0.7157142857142857|15.981344        | 
| AllGestureWiimoteZ|0.6757142857142857|13.106202        | 
| ArrowHead|0.8571428571428571|1.481234                  | 
| ArticularyWordRecognition|0.9966666666666667|16.601666 | 
| AtrialFibrillation|0.2|1.490244                        | 
| BME|0.9933333333333333|0.842719                        | 
| BasicMotions|1.0|1.438721                              | 
| Beef|0.8333333333333334|1.08501                        | 
| BeetleFly|0.95|0.96993                                 | 
| BirdChicken|0.9|1.009865                               |

Current results on main (original train test split) :
| Name                                   | Acc  | time  |
|--------------------------------|---|---|
|ACSF1|0.93|33.765473|
|Adiac|0.7340153452685422|12.60369|
|AllGestureWiimoteX|0.7128571428571429|38.506022|
|AllGestureWiimoteY|0.71|38.440987|
|AllGestureWiimoteZ|0.69|38.416986|
|ArrowHead|0.8628571428571429|4.390125|
|ArticularyWordRecognition|0.9933333333333333|33.320754|
|AtrialFibrillation|0.2|3.248225|
|BME|0.9933333333333333|2.330296|
|BasicMotions|1.0|2.900055|
|Beef|0.8666666666666667|2.638048|
|BeetleFly|0.95|2.430503|
|BirdChicken|0.9|2.444238|

### CODE REVIEW

**Comment by baraline** [comment]
Concerning RDST and RIST regressor failure, I got different values now from `regressor_results_reproduction.py` than from the ones stored in `expected_regressor_outputs.py` :
```
RDSTRegressor - Covid3Month
[
0.0687,
0.071,
0.0227,
0.0425,
0.0834,
0.0251,
0.0064,
0.1398,
0.0667,
0.031,
]

RISTRegressor - CardanoSentiment
[
0.0412,
0.3174,
0.3174,
0.0412,
0.1924,
0.0,
0.0,
0.0412,
0.0825,
0.3503,
]
```
```
System:
    python: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\antoine\anaconda3\envs\aeon_dev\python.exe
   machine: Windows-10-10.0.22631-SP0

Python dependencies:
         aeon: 0.11.1
          pip: 23.3.1
   setuptools: 68.0.0
 scikit-learn: 1.2.2
        numpy: 1.24.4
        numba: 0.58.1
        scipy: 1.11.4
       pandas: 2.0.3
```
Could anyone check if the results matches on their side ?

**Comment by baraline** [comment]
I can't seem to figure out why the RDST / RIST are failing, on both windows and Linux I'm getting consistent result locally with the test method... So putting this out for review as it will still help with the cache corruption issue.

**Review by TonyBagnall — APPROVED** [review]
LGTM

**Comment by TonyBagnall** [comment]
actually could this wait until #2138 ? It will conflict on the test config, easier to fix this one after

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
