### PR TITLE
[MNT] Release 0.7.1

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Release 0.7.1

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
Could we hold this off to wait for #1271 ?

**Comment by MatthewMiddlehurst** [comment]
I was planning on doing this tomorrow, so unless it is going to be quick it would be better if it can wait.

**Comment by hadifawaz1999** [comment]
> I was planning on doing this tomorrow, so unless it is going to be quick it would be better if it can wait.

I insisted if we can wait for the PR because its a bug, which means no user can correctly use the random_state, but happy to let it wait if its not possible to get it in before the release

**Review by baraline — APPROVED** [review]
Not much to say, LGTM !

**Pull request merged**
