### PR TITLE
[DOC] fixed path of image

### PR DESCRIPTION
**Pull request by hadifawaz1999**
Fixed an image path for the deep learning notebook.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
for the other folders, I have created an img directory in the sub dir and moved pictures there, so that img/H-Inception.png would work. Might be better to duplicate this structure for networks

**Comment by hadifawaz1999** [comment]
> for the other folders, I have created an img directory in the sub dir and moved pictures there, so that img/H-Inception.png would work. Might be better to duplicate this structure for networks

Oh okay will do that then thanks ! do you use the H-Inception image in some notebooks in root ? if not i can move it instead of duplicate the image.

**Comment by TonyBagnall** [comment]
> > for the other folders, I have created an img directory in the sub dir and moved pictures there, so that img/H-Inception.png would work. Might be better to duplicate this structure for networks
> 
> Oh okay will do that then thanks ! do you use the H-Inception image in some notebooks in root ? if not i can move it instead of duplicate the image.

move it rather than copy, dont think its used elsewhere, will check after

**Comment by hadifawaz1999** [comment]
> > > for the other folders, I have created an img directory in the sub dir and moved pictures there, so that img/H-Inception.png would work. Might be better to duplicate this structure for networks
> > 
> > 
> > Oh okay will do that then thanks ! do you use the H-Inception image in some notebooks in root ? if not i can move it instead of duplicate the image.
> 
> move it rather than copy, dont think its used elsewhere, will check after

Should be good now, let me know. I checked and its not used in other notebooks.

**Comment by hadifawaz1999** [comment]
Should i wait till we fix the kalman stuff and other packages that were updated @TonyBagnall @MatthewMiddlehurst ? because the fails are because of that.

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
