### PR TITLE
[DOC] Seperated Notes and References

### LINKED ISSUE #2280: [DOC] Replace NOTES by REFERENCES in docstrings
### Describe the issue linked to the documentation

Noticed that some docstrings use NOTES instead of REFERENCES in docstrings, making the api doc not linking refs correctly

### Suggest a potential alternative/fix

just should be replaced, i noticed it in some deep learners but would be good to do a check all over aeon at some point

### PR DESCRIPTION
**Pull request by aryanpola**
#### What does this implement/fix? Explain your changes.
Fixes #2280 
Separated Notes and References.

### CODE REVIEW

**Review by MatthewMiddlehurst — COMMENTED** [review]
Can you put the notes section above references

**Comment by aryanpola** [comment]
@MatthewMiddlehurst any reason for the error?

**Comment by hadifawaz1999** [comment]
> @MatthewMiddlehurst any reason for the error?

no reason, random fail, re-ran the failed job

**Review by TonyBagnall — APPROVED** [review]
LGTM, thanks

**Pull request merged**
