### PR TITLE
[ENH] Included RSAST as a alternative to SAST

### PR DESCRIPTION
**Pull request by nirojasva**
#### What does this implement/fix? Explain your changes.

I included a transformer RSAST and a classifier RSASTClassifier which are tools to use in time series classification. The method RSAST is based on shapelets in order to transform dataset of Time Series.

#### Does your contribution introduce a new dependency? If yes, which one?
 
Yes, I used f_oneway, DegenerateDataWarning, ConstantInputWarning from the "scipy.stats" toolkit. Also,  acf and pacf from the "statsmodels.tsa.stattools" implementation.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by nirojasva** [comment]
Hi, I'm new to using forks on github. I already changed the __init__.py file, including a "LearningShapeletClassifier" classifier that I thought was causing conflicts with the code I'm trying to merge. However, I have not been able to complete the PR. What else should I check to correctly modify the code? Thanks for the help.

**Comment by MatthewMiddlehurst** [comment]
Hi @nirojasva, you will want to pull from the main `branch` main repository remote `aeon-toolkit/aeon`, then resolve any conflicts.

How different is this from the original SAST, can it be integrated into that implementation instead? I think @TonyBagnall reviewed the original?

**Comment by nirojasva** [comment]
Hi @MatthewMiddlehurst, 

Yes, it is a little bit different since in SAST every subsequence in time series is extracted for the transformation of dataset and in RSAST just some randomly selected shapelet are used to do the transformation. 

I have about the validation, if I make push from my local aeon github project it will automaticlly recalcalculate the conflicts?

Thanks,

**Comment by MatthewMiddlehurst** [comment]
It sounds like this could be in the same classifier as the regular SAST as a parameter (like the ROCKET variants). If the transformer can't be in the same class, it could be in the same file to keep it more organised.

> I have about the validation, if I make push from my local aeon github project it will automaticlly recalcalculate the conflicts? 

No, you will have to pull the `main` branch first. After merging there, you can then push the merged commits to your branch and it will update here.

**Comment by nirojasva** [comment]
It seems now is merged, thanks.

**Comment by MatthewMiddlehurst** [comment]
For this branch it looks like you overwrote the contents with main rather then merging. You may have to create a new PR, or maybe adding new changes will reopen.

**Comment by nirojasva** [comment]
I tried to create another PR: [ENH] Included RSAST as a alternative to SAST (2.0) #1383

**Pull request closed without merging**
