### PR TITLE
[ENH,REF] Refactor `univariate-only` tag

### PR DESCRIPTION
**Pull request by itsdivya1309**
#### Reference Issues/PRs
Fixes: #812 

#### What does this implement/fix? Explain your changes.

Refactor `univariate-only` tag to `capability:multivariate` and accordingly update the tests.

### CODE REVIEW

**Review by TonyBagnall — COMMENTED** [review]
this looks good to me, and is a big chunk of work, thanks! It changes so many files I'll leave it open for a bit in case others want to comment

**Comment by itsdivya1309** [comment]
Hi @TonyBagnall! 
I was wondering if I should update the [tags registry](https://github.com/aeon-toolkit/aeon/blob/v0.8.0/aeon/registry/_tags.py) as well? Once this PR is merged, the `univariate-only` lag will only be used in forecasting.

**Comment by TonyBagnall** [comment]
> Hi @TonyBagnall! I was wondering if I should update the [tags registry](https://github.com/aeon-toolkit/aeon/blob/v0.8.0/aeon/registry/_tags.py) as well? Once this PR is merged, the `univariate-only` lag will only be used in forecasting.

not sure atm, but I think get this in first, forecasting is a little bit there be dragons ....I'll leave it until friday for further comments

**Review by TonyBagnall — APPROVED** [review]

**Review by baraline — APPROVED** [review]
The described change seems to be applied correctly to all listed files. So LGTM !

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
