### PR TITLE
[MNT] Make deep learning  private (classification / regression / networks)

### LINKED ISSUE #174: [ENH] Make the deep learning classifiers private
After the current classification will be merged, I will be taking care of this issue. Basically using the underscore prefix and import them in the ```__init__.py``` script.

### PR DESCRIPTION
**Pull request by hadifawaz1999**
#### Reference Issues/PRs
Resolve #174 

#### What does this implement/fix? Explain your changes.
Make deep learners private for classification and regression, the network module as well.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
this is why I didnt do it when I put the init in :) Need to track down notebook and other references

**Comment by MatthewMiddlehurst** [comment]
May be good to get this in before deprecation if you can find the capacity @hadifawaz1999

**Comment by hadifawaz1999** [comment]
> May be good to get this in before deprecation if you can find the capacity @hadifawaz1999

we did lots of changes on this module since then, if i am able to do it before deprecation i will have to remake a new PR

**Comment by MatthewMiddlehurst** [comment]
@TonyBagnall can this be closed?

**Comment by hadifawaz1999** [comment]
> @TonyBagnall can this be closed?

yes we can, @TonyBagnall took care of it in a sep PR

**Pull request closed without merging**
