### PR TITLE
[MNT] Rename package to aeon

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Renames the base package to `aeon`. Temporarily changes requirement for linting.

- excluded `build_tools` dir from pre-commit checks
- excluded all `tests/__init__.py` from `pydocstyle` pre-commit checks

### CODE REVIEW

**Comment by aiwalter** [comment]
could you add in the PR description the exact bulk replaces you did? Just in case in future we realize sth is broken

**Comment by MatthewMiddlehurst** [comment]
Other than using pycharm to refactor the base directory, there was no bulk find & replace

**Review by GuzalBulatova — COMMENTED** [review]
Looks like all is renamed, thank you @MatthewMiddlehurst ! code-quality is failing, seems that it can be fixed with pre-commit hooks?

**Comment by MatthewMiddlehurst** [comment]
I tried that in a previous PR, but got an ImportError in forecasting (https://github.com/aeon-toolkit/aeon/actions/runs/4384819164/jobs/7676751541). 

If anyone knows why that happened I can try run it through pre-commit. May be better just to let it lie for now.

**Comment by GuzalBulatova** [comment]
Could you please send a link / name of the commit? I can only see the pointer to the branch and the PR in the job summary

**Comment by MatthewMiddlehurst** [comment]
I believe this is the commit where I let pre-commit do its thing on the whole repo. The branch is gone now, unfortunately. I just deleted and replaced it with this. https://github.com/aeon-toolkit/aeon/pull/183/commits/dba5fd6965867da486ebacb25d719f3b18f5f632

**Review by aiwalter — APPROVED** [review]

**Comment by lmmentel** [comment]
I can have a look and try to fix the commit. Let me know

**Review by lmmentel — APPROVED** [review]
:tada:

**Pull request merged**
