### PR TITLE
[MNT] Fix random test failure in FeatureSelection

### LINKED ISSUE #158: [MNT] Investigate random state failure in test_feature_selection[None-2-random]
test `test_feature_selection[None-2-random]` was failing "randomly", need to investigate it.

pipeline: https://github.com/aeon-toolkit/aeon/actions/runs/4344052231/jobs/7587082413

### PR DESCRIPTION
**Pull request by aiwalter**
closes #158

### CODE REVIEW

**Comment by lmmentel** [comment]
Hey, how about dropping the parametrization over random seeds? Not sure it adds any extra coverage.

**Review by TonyBagnall — APPROVED** [review]

**Comment by TonyBagnall** [comment]
> Hey, how about dropping the parametrization over random seeds? Not sure it adds any extra coverage.

I agree, no point testing two random seeds. Fewer tests is a good thing

**Comment by aiwalter** [comment]
> Hey, how about dropping the parametrization over random seeds? Not sure it adds any extra coverage.

The coverage is that this test makes sure that `"random"` is actually doing sth random :) So lets keep it, now it should not fail anymore

**Comment by MatthewMiddlehurst** [comment]
Have to agree with Tony and Lukasz really, it is essentially doubling the time this test takes every PR unnesessarily. If we did this kind of parameterisation in other modules we would be spending 4 hours sitting around. Things like this are prime candidates to cut for reducing the time spent testing.

**Pull request merged**
