### PR TITLE
[DOC, ENH] Updating distance's notebooks + tests to ensure sklearn compatibility

### PR DESCRIPTION
**Pull request by dguijo**
#### Reference Issues/PRs
Part of #1654

#### What does this implement/fix? Explain your changes.

- Modifies and updates the sklearn_distances notebook to ensure consistency and to demonstrate the full usage of the distances module implemented in aeon. 
- Tests involving KNeighborsTimeSeriesClassifier have also been updated and enhanced. Same changes have been made for KNeighborsTimeSeriesRegressor.

#### Does your contribution introduce a new dependency? If yes, which one?

None.

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [X] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Review by MatthewMiddlehurst — COMMENTED** [review]
Would like input from @chrisholder and @TonyBagnall since this mostly covers distances. Mostly on if there is any issues/redundancy with the new tests and the parameter change.

I have a feeling changing the default from 1 to 5 may cause some issues.

**Comment by dguijo** [comment]
Hello @MatthewMiddlehurst @TonyBagnall, 

I've reverted the changes concerning the default `k` value for both TSC and TSER. 
Hence, this PR just updates the current distance's notebook (not KDD one), and enhances the sklearn compatibility's tests. 

Have a nice day/week :)

**Comment by MatthewMiddlehurst** [comment]
non-notebook changes look good. Not had a in-depth read through of the sklearn notebook yet but the data structures one is not showing the correct diff on the viewer and there seems to be an error. Could you re-run if the changes to it were intentional?

**Comment by dguijo** [comment]
> non-notebook changes look good. Not had a in-depth read through of the sklearn notebook yet but the data structures one is not showing the correct diff on the viewer and there seems to be an error. Could you re-run if the changes to it were intentional?

Thank you, @MatthewMiddlehurst. You're right, the changes to the data_structures notebook weren't intentional 😃. Not sure what happened. Sorry! Should be fine now!

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
