### PR TITLE
[BUG] Fixed subsampling in highly imbalances datasets giving subsamples with only a single class

### LINKED ISSUE #1726: [BUG] HC2 sporadic CI failure
### Describe the issue

See https://github.com/aeon-toolkit/aeon/actions/runs/9676429469/job/26695950355

### Suggest a potential alternative/fix

Appears to be related to TDE `fit_predict`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ferewi**
#### Reference Issues/PRs
Fixes #1726 

#### What does this implement/fix? Explain your changes.
Added new attribute 'max_subsamples' to subsample multiple times in case of unbalanced datasets giving subsamples with only one class. This caused TDE and HC2 to fail.
If a subsample with only a sinlge class is found, subsampling is repeated until the number of classes in the subsample is >1 or until max_subsamples is reached. In the latter case an AttributeError is raised.

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### Any other comments?
In the Issue I proposed two ideas how to fix this and I went for a modified option 1 that does not lead to potentially infinite loops as it is more than 3 times faster compared to option 2 (StratifiedShuffleSplit).

### PR checklist
@all-contributors add @ferewi for code

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
does not apply
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
does not apply
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Review by MatthewMiddlehurst — COMMENTED** [review]
Is there a situation where you wouldn't want to continue until there is a viable subsample? I would just use a while loop and continue until you do. 

The only time this will backfire is if there is only 1 class in the input, but we should catch that higher up in input verification IMO.

**Comment by ferewi** [comment]
I was a bit caught up last week hence my late reply. @MatthewMiddlehurst I think your're right, the new parameter is actually not needed. I was thinking that given a large unbalanced dataset, the chance for drawing a subsample that contains just one class is high, but given the subsample size of 70% this chance is around 0.5 in the worst case. So just resampling until a valid sample is obtained should be fine.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
LGTM, thanks.

**Comment by MatthewMiddlehurst** [comment]
@all-contributors add @ferewi for bug

**Pull request merged**
