### PR TITLE
[ENH] Rework distance/matrix profile import system 

### PR DESCRIPTION
**Pull request by aryanpola**
What does this implement/fix? Explain your changes.
#2021 Implemented lazy loading for `query_search` under similarity searching.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

### CODE REVIEW

**Comment by aryanpola** [comment]
@baraline Please let me know if everthing's okay with changes made.

**Comment by MatthewMiddlehurst** [comment]
I would want some justification before merging any of these changes. It makes the code more confusing, so unless some significant benefit is shown I wouldn't want it in.

**Comment by baraline** [comment]
Hey, I had in mind was a bit more naïve that than this. 
I would have just made a function that import the function as follow : 
```
if distance == "euclidean" and normalize :
    from ... import normalized_euclidean
    return normalized_euclidean
```
The goal was to reduce import time of the estimators, considering this imports a lot of numba code if we load all imports. I could benchmark to measure the impact. But I agree that the proposed implementation might be too complex for our need.

**Comment by aryanpola** [comment]
@MatthewMiddlehurst @baraline I was going through open issues and found #1852, which wants to reduce the import time for packages. So, I implemented lazy loading from their docs.
https://scientific-python.org/specs/spec-0001/

Before implementing lazy loading:
```
Time to import numpy: 0.000001 seconds
Time to import numba: 0.000000 seconds
Time to import aeon.distances: 0.000001 seconds
Time to import aeon.similarity_search._commons: 0.000000 seconds
Time to import aeon.similarity_search.base: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles: 0.000001 seconds
Time to import aeon.similarity_search.distance_profiles.euclidean_distance_profile: 0.000001 seconds
Time to import aeon.similarity_search.distance_profiles.squared_distance_profile: 0.000000 seconds
Time to import numpy: 0.000000 seconds
Time to import numba: 0.000000 seconds
Time to import aeon.distances: 0.000001 seconds
Time to import aeon.similarity_search._commons: 0.000000 seconds
Time to import aeon.similarity_search.base: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles.euclidean_distance_profile: 0.000001 seconds
Time to import aeon.similarity_search.distance_profiles.squared_distance_profile: 0.000000 seconds
```

After lazy loading:
```
Time to import numpy: 0.000000 seconds
Time to import numba: 0.000000 seconds
Time to import aeon.distances: 0.025223 seconds
Time to import aeon.similarity_search._commons: 0.000001 seconds
Time to import aeon.similarity_search.base: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles: 0.000001 seconds
Time to import aeon.similarity_search.distance_profiles.euclidean_distance_profile: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles.squared_distance_profile: 0.000001 seconds
Time to import numpy: 0.000000 seconds
Time to import numba: 0.000001 seconds
Time to import aeon.distances: 0.000000 seconds
Time to import aeon.similarity_search._commons: 0.000000 seconds
Time to import aeon.similarity_search.base: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles.euclidean_distance_profile: 0.000000 seconds
Time to import aeon.similarity_search.distance_profiles.squared_distance_profile: 0.000000 seconds
```
The time for importing some modules increased and I don't know the reason for it.

**Comment by baraline** [comment]
Indeed, a bit weird, don't know much about the lazy import stuff, but that seems counterintuitive. How did you measure these timings? Maybe the reason is in there instead

**Comment by aryanpola** [comment]
> Indeed, a bit weird, don't know much about the lazy import stuff, but that seems counterintuitive. How did you measure these timings? Maybe the reason is in there instead

Really sorry for the delayed reply.
Here's how I measure the time.
```
import time

def timed_import(library_name):
    start_time = time.time()
    _import_(library_name)
    end_time = time.time()
    print(f"Time to import {library_name}: {end_time - start_time:.6f} seconds")

libraries = [
    "numpy",
    "numba",
    "aeon.distances",
    "aeon.similarity_search._commons",
    "aeon.similarity_search.base",
    "aeon.similarity_search.distance_profiles",
    "aeon.similarity_search.distance_profiles.euclidean_distance_profile",
    "aeon.similarity_search.distance_profiles.squared_distance_profile",
]

for lib in libraries:
    timed_import(lib)
```

**Comment by baraline** [comment]
We're not rushing, not problem!

Could you try to measure it multiple time for each import and report the average and standard deviations for each instead of a single timing?
Alternatively, if you are doing all this with a IPython (Jupyter etc ...), you could call 
`timings = %timeit -q -o import ....`
and then you'll have the average and stds as `timings.average` and `timings.stdev`

**Comment by aryanpola** [comment]
> We're not rushing, not problem!
> 
> Could you try to measure it multiple time for each import and report the average and standard deviations for each instead of a single timing? Alternatively, if you are doing all this with a IPython (Jupyter etc ...), you could call `timings = %timeit -q -o import ....` and then you'll have the average and stds as `timings.average` and `timings.stdev` Also, the worse ones might be interesting for what we are trying to diagnose (`timings.worst`)

```
import time
import statistics

def timed_import(library_name, n_iterations=10):
    """Measures the time it takes to import a library."""
    times = []
    for _ in range(n_iterations):
        start_time = time.time()
        importlib.import_module(library_name)
        end_time = time.time()
        times.append(end_time - start_time)
    
    avg_time = sum(times) / n_iterations
    std_dev = statistics.stdev(times)
    worst_time = max(times)
    
    print(f"{library_name}:")
    print(f"  Average Time: {avg_time:.6f} seconds")
    print(f"  Standard Deviation: {std_dev:.6f} seconds")
    print(f"  Worst Time: {worst_time:.6f} seconds")
    print()

libraries = [
    "numpy",
    "numba",
    "aeon.distances",
    "aeon.similarity_search._commons",
    "aeon.similarity_search.base",
    "aeon.similarity_search.distance_profiles",
    "aeon.similarity_search.distance_profiles.euclidean_distance_profile",
    "aeon.similarity_search.distance_profiles.squared_distance_profile",
]

for lib in libraries:
    timed_import(lib)
```
The output is :
```
Lazy import of normalized_euclidean_distance_profile took 0.0239 seconds.
Lazy import of normalized_euclidean_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of euclidean_distance_profile took 0.0000 seconds.
Lazy import of euclidean_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of normalized_squared_distance_profile took 0.0000 seconds.
Lazy import of normalized_squared_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of squared_distance_profile took 0.0000 seconds.
Lazy import of squared_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
numpy:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

numba:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.distances:
  Average Time: 0.006247 seconds
  Standard Deviation: 0.019755 seconds
  Worst Time: 0.062471 seconds

aeon.similarity_search._commons:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.base:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles.euclidean_distance_profile:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles.squared_distance_profile:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

<frozen runpy>:128: RuntimeWarning: 'aeon.similarity_search.query_search' found in sys.modules after import of package 'aeon.similarity_search', but prior to execution of 'aeon.similarity_search.query_search'; this may result in unpredictable behaviour
Lazy import of normalized_euclidean_distance_profile took 0.0000 seconds.
Lazy import of normalized_euclidean_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of euclidean_distance_profile took 0.0000 seconds.
Lazy import of euclidean_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of normalized_squared_distance_profile took 0.0000 seconds.
Lazy import of normalized_squared_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
Lazy import of squared_distance_profile took 0.0000 seconds.
Lazy import of squared_distance_profile took 0.0000 seconds.
Lazy import of naive_distance_profile took 0.0000 seconds.
numpy:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

numba:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.distances:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search._commons:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.base:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles.euclidean_distance_profile:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds

aeon.similarity_search.distance_profiles.squared_distance_profile:
  Average Time: 0.000000 seconds
  Standard Deviation: 0.000000 seconds
  Worst Time: 0.000000 seconds
```

**Comment by baraline** [comment]
Thanks ! Seeing those timings, maybe this is a non-issue ... I'll check again this evening if I can replicate what I was noticing at the time of the issue and keep you updated.

**Comment by baraline** [comment]
Hi @aryanpola, I can't seem to reproduce the problem I had when raising the issue, new install or not. I'll close this PR and the associated issue for now, but thanks for pointing out the lazy import system, it might get useful in the future!

**Comment by aryanpola** [comment]
Hi, @baraline if there are any new issues related to lazy loading, please let me know. 
Thanks!

**Comment by aadya940** [comment]
I don't think there is much of a way to measure the import times of lazy imports, since when you `import` stuff, if something is truly `lazy`, it will never be imported till used. Also, just to clarify a bit, I  opened #1852 to reduce import times on heavy weight packages that might end up never being used but still imported which are majorly external packages, so I'd say not to lazy load internal `aeon` modules. The goal was minimize the junk in [CPU Swap Space](https://en.wikipedia.org/wiki/Memory_paging).

**Pull request closed without merging**
