### PR TITLE
[MNT] Replaced assert with raise ValueError messages in networks module

### LINKED ISSUE #1956: [MNT] Replace assertions in networks module with raising Value errors
### Describe the issue

In all networks module, the parameters handled as input lists have an assertion for the length of the list, but assertions are not a good idea, they should be replaced by raise ValueError message

### Suggest a potential alternative/fix

Example

instead of:
```Python
assert len(self.strides) == self.n_conv_per_residual_block
```
It should be :

```Python
if len(self.strides) != self.n_conv_per_residual_block:
    raise ValueError(
        f"Number of strides {len(self.strides)} should be"
        f" the same as number of convolution layers per block but is"
        f" not: {self.n_conv_per_residual_block}."
    )
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by notaryanramani**
#### Reference Issues/PRs
Issue #1956 
Closes #1956 

#### What does this implement/fix? Explain your changes.
Replaces assertions in networks module with raising ValueError messages

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
@all-contributors add @notaryanramani for code

**Comment by TonyBagnall** [comment]
thanks for this, looks good to me but will wait for @hadifawaz1999 or @aadya940 to take a look

**Comment by aadya940** [comment]
@notaryanramani @TonyBagnall Apart from the comments, LGTM! 👍

**Comment by TonyBagnall** [comment]
@all-contributors add @notaryanramani for code

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
