### PR TITLE
[ENH,MNT,DOC] Tidying up deep learning modules clasification/regression

### LINKED ISSUE #1602: [ENH] Add possibility to save deep learning models at initialization
### Describe the feature or idea you want to propose

Usually, we can save a model at initialization (before training) to insure reproducibility. Even though we could fixe the random state, it may also be interesting to add this feature.

### Describe your proposed solution

Add a parameter like 'save_initialization' to save the Keras initialized model

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hadifawaz1999**
- Add inititalization saving capability to deep learners Fix #1602 
- add deprecation to CNNNetwrork, CNNClassifier, CNNRegressor replace with TimeCNN...
- fix some doc stuff
- missing api stuff
- added test for save/load on all deep learners for best/last/init models

### CODE REVIEW

**Review by baraline — COMMENTED** [review]
Tests make sense with the additions / modifications, and didn't pick up anything weird or missing docstring.

Just one note, to respect deprecation policy, shouldn't you mark them for removal for version 0.12 ( or 1.0 ) instead of 0.11 ? As these changes will be displayed in the next release (0.11) ( Or did I missunderstood the policy ? )

**Comment by hadifawaz1999** [comment]
> Tests make sense with the additions / modifications, and didn't pick up anything weird or missing docstring.
> 
> Just one note, to respect deprecation policy, shouldn't you mark them for removal for version 0.12 ( or 1.0 ) instead of 0.11 ? As these changes will be displayed in the next release (0.11) ( Or did I missunderstood the policy ? )

i think you are right, @MatthewMiddlehurst @TonyBagnall should we put 0.12.0 or 1.0..0 ?

**Review by baraline — APPROVED** [review]
Guess we'll suppose 0.12 for now? Can edit later to change it to 1.0 if needed.

**Comment by hadifawaz1999** [comment]
> Guess we'll suppose 0.12 for now? Can edit later to change it to 1.0 if needed. If you wanna wait for Matthew or Tony comment on this no issue.

the reason is i think its not 100% sure there wont be a 0,12, so if there isnt will pr the change, thanks

**Pull request merged**
