### PR TITLE
[ENH] Update `VARMAX` pandas 2.0

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
updated pandas version to 2.0

#### Reference Issues/PRs
#291

### CODE REVIEW

**Comment by AnonymousCodes911** [comment]
@MatthewMiddlehurst, is this change a fix, or should we deprecate certain functions to ensure compatibility? local Tests are currently being skipped due to the absence of soft dependencies.

**Comment by AnonymousCodes911** [comment]
@MatthewMiddlehurst , Thanks! I will work accordingly.

**Comment by MatthewMiddlehurst** [comment]
I think it's best to leave this for now, IMO. We have some significant changes to the module planned which may make this irrelevant either way.

**Comment by AnonymousCodes911** [comment]
I see, I ll Close this for now!

**Pull request closed without merging**
