### PR TITLE
[MNT] Increase test speed for rdst

### LINKED ISSUE #1060: [MNT] Increase test speed for RDST
### Describe the issue

During CI test, RDST and some method used (prime dilation) take a lot of time to test and are often in the top-20 of slowest test duration.

- [ ] Investigate the conditions under which these test are slow
- [ ] Try to improve the testing speed without sacrificing coverage
- [ ] Give another shot to #324 with these changes

### Suggest a potential alternative/fix

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by baraline**
#### Reference Issues/PRs

Fixes #1060 

#### What does this implement/fix? Explain your changes.

Try to improve testing speed for RDST by fixing some numba deprecation and reducing the number of shapelets used during tests. If this makes things better, we can move on to #324.

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [X] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

### CODE REVIEW

**Comment by baraline** [comment]
150.09s call     aeon/testing/test_all_estimators.py::TestAllEstimators::test_non_state_changing_method_contract[RDSTClassifier-ClassifierFitPredictMultivariate-predict_proba]
139.16s call     aeon/testing/test_all_estimators.py::TestAllEstimators::test_fit_updates_state[RDSTClassifier-ClassifierFitPredictUnequalLength]
114.90s call     aeon/transformations/collection/shapelet_based/tests/test_dilated_shapelet_transform.py::test_shapelet_prime_dilation

This had no effect on the issue, @MatthewMiddlehurst, these estimator tests are run with numba right ? If so numba compilation might be the culprit, I'll look at ways to reduce it if that's the case.

**Comment by MatthewMiddlehurst** [comment]
Maybe wait for #849 first, see if that makes a difference.

**Comment by baraline** [comment]
It seems from period test results that #849 fixed RDST being the slowest test and greatly improved test speed, so I guess this PR is not needed anymore right @MatthewMiddlehurst  ?

**Comment by MatthewMiddlehurst** [comment]
Feel free to repurpose this, but yeah it seems the numba changes had a positive impact.

**Pull request closed without merging**
