### PR TITLE
[ENH] Remove top of file warnings for soft dependencies

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Current procedure for soft dependencies is to top a warning when imported if the soft dependency package is missing.

IMO, this does not accomplish much. Either you are directly using the contents of the package and will run into an error because of the missing dependency anyway with the relevant information, or you are indirectly importing the contents while using surrounding functionality in which case the warning is not required.

I think it would remove a lot of output clutter if we remove them. People are welcome to give their thoughts on the current procedure and the usefulness of these warnings.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
I'm in favour of this and would also maybe remove even the option of warning/error, just throw an informative error (in a later PR). There  is too much over parameterised code

**Comment by lmmentel** [comment]
Looks good and I agree mostly. The thing we loose here is the ability to control the message that is going to presented back to the user. Out of curiosity have you checked what messages you get when importing all modules with that depend of soft deps but those are not installed?

**Comment by MatthewMiddlehurst** [comment]
We still use the function elsewhere, just raising errors instead of warnings (and not at the import level). We test to make sure that the error is raised for soft deps as far as I am aware.

I just checked, and the exact same message is raised for warnings and errors. This is the only part of the function the `severity` parameter effects:

image

**Comment by MatthewMiddlehurst** [comment]
i.e. for the following with no package installation

```python
from aeon.transformations.collection import TSFreshFeatureExtractor

if __name__ == "__main__":
    print(TSFreshFeatureExtractor())
```

warning:
image

error;
image


both will be displayed currently, i.e.

```python-traceback
D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\collection\tsfresh.py:13: UserWarning: No module named 'tsfresh'. 'tsfresh' is a soft dependency and not included in the base aeon installation. Please run: `pip install tsfresh` to install the tsfresh package. To install all soft dependencies, run: `pip install aeon[all_extras]`
  _check_soft_dependencies("tsfresh", severity="warning")
Traceback (most recent call last):
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\utils\validation\_dependencies.py", line 118, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "C:\Users\Matthew Middlehurst\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tsfresh'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\CMP Machine Learning\Other Code\release-test\test.py", line 4, in <module>
    print(TSFreshFeatureExtractor())
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\collection\tsfresh.py", line 243, in __init__
    super(TSFreshFeatureExtractor, self).__init__(
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\collection\tsfresh.py", line 54, in __init__
    super(_TSFreshFeatureExtractor, self).__init__()
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\collection\base.py", line 58, in __init__
    super(BaseCollectionTransformer, self).__init__(_output_convert=False)
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\base.py", line 151, in __init__
    _check_estimator_deps(self)
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\utils\validation\_dependencies.py", line 364, in _check_estimator_deps
    pkg_deps_ok = _check_soft_dependencies(*pkg_deps, severity=severity, obj=obj)
  File "D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\utils\validation\_dependencies.py", line 140, in _check_soft_dependencies
    raise ModuleNotFoundError(msg) from e
ModuleNotFoundError: TSFreshFeatureExtractor requires package 'tsfresh' to be present in the python environment, but 'tsfresh' was not found. 'tsfresh' is a soft dependency and not included in the base aeon installation. Please run: `pip install tsfresh` to install the tsfresh package. To install all soft dependencies, run: `pip install aeon[all_extras]`
```

**Comment by MatthewMiddlehurst** [comment]
importing something else from the same package as tsfresh will still give the warning due to it being in the same `__init__`. i.e. the above but printing Catch22:

```python-traceback
D:\CMP Machine Learning\Other Code\release-test\venv\lib\site-packages\aeon\transformations\collection\tsfresh.py:13: UserWarning: No module named 'tsfresh'. 'tsfresh' is a soft dependency and not included in the base aeon installation. Please run: `pip install tsfresh` to install the tsfresh package. To install all soft dependencies, run: `pip install aeon[all_extras]`
  _check_soft_dependencies("tsfresh", severity="warning")
Catch22()
```

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
