### PR TITLE
[MNT] `dask` CI fix, ReadTheDocs fix and expanded full pytest actions tag

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Stops `dask` from crashing the Python 3.11 CI by lowering the version bound again. If someone wants `dask` for these versions, they will have to update to the latest version and resolve the resulting issues.

Updates the full pytest tag to use all Python versions in PRs.

### CODE REVIEW

**Review by TonyBagnall — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
Im going to run this without the tag quick just to check its still ok.

**Review by TonyBagnall — APPROVED** [review]
lgtm

**Comment by MatthewMiddlehurst** [comment]
nope, still a bit broken unfortunately 🙁. No idea why it is running all Python versions without the tag

**Comment by MatthewMiddlehurst** [comment]
Ok looks good now. Also fixed a Sphinx issue thats going to impact every PR. Suddenly popped up while testing this.

**Review by TonyBagnall — APPROVED** [review]
not sure how long overnight will take with all versions

**Pull request merged**
