### PR TITLE
[MNT] Recursively find notebooks for testing

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Edits the notebook test script to recursively select notebooks. Currently notebooks in subdirectories are not being tested I believe.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
@TonyBagnall I think some of the new classification notebooks may have an error picked up because of this change

**Comment by TonyBagnall** [comment]
great find, I assumed they were being tested. Funnily I just read a notebook and wondered how it passed!

**Comment by TonyBagnall** [comment]
shall I fix them on this branch?

**Comment by MatthewMiddlehurst** [comment]
No issue here if you want to push changes to this

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
