### PR TITLE
[ENH] Refactoring PAA

### PR DESCRIPTION
**Pull request by hadifawaz1999**
#### Reference Issues/PRs
Part of #434 

#### What does this implement/fix? Explain your changes.
Refactors PAA to become faster

The only input parameter is the number of segments, or in other words, the target dimension.
Basically for the transformation can be done in:
- One line, parallelized over all samples and dimensions if and only if the length of the TS is divisible by the number of segments
- A for loop on the segments split indices, still parallelized, only in the case of non divisibility

#### What should a reviewer concentrate their feedback on?
The optimality and correctness of the PAA refactor

#### Did you add any tests for the change?
Refactored the PAA test

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
The implementation includes as well an `inverse_paa` function to produce the following, this is mostly for visual aid:

image

**Comment by patrickzib** [comment]
It is a great improvement over the previous version. Well done. 

One issue in combination with SAX: where do we make sure that the input data is z-normalized when transformed with SAX? As of now, PAA does not apply z-normalization to the time series. Same for SAX, right?

**Comment by patrickzib** [comment]
> @patrickzib I had the same question in my head :p is where to include it now, the simplest solution is to have `znormalized` parameter into both, this way if the user is using SAX or PAA, the data will always be znormalized. But wanted to see what you think before doing that.

Yes, maybe add a parameter to SAX: z-normalize, defaulted to True. When set to true, it applies z-norm to the input time series. This way, you do not have to modify PAA.

**Comment by patrickzib** [comment]
The more sophisticated option would be to set the SAX breakpoints from the actual data. I.e. compute the mean and std from the time series and set it for the Gaussian distribution as input prior to computing the breakpoints.

**Comment by hadifawaz1999** [comment]
> > @patrickzib I had the same question in my head :p is where to include it now, the simplest solution is to have `znormalized` parameter into both, this way if the user is using SAX or PAA, the data will always be znormalized. But wanted to see what you think before doing that.
> 
> Yes, maybe add a parameter to SAX: z-normalize, defaulted to True. When set to true, it applies z-norm to the input time series. This way, you do not have to modify PAA.

But if someone uses PAA only (no SAX involved), shouldn't the input time series also be znormalized ? I should check the original paper because not sure if its an obligation such as in SAX

**Comment by hadifawaz1999** [comment]
> 

Thats actually a good idea, will make it an argument maybe ? to either manually choose them or automatically generate them from the data

**Comment by patrickzib** [comment]
> But if someone uses PAA only (no SAX involved), shouldn't the input time series also be znormalized ? I should check the original paper because not sure if its an obligation such as in SAX

PAA should not depend on the normalization of the data. It was a trick in SAX to be able to have constant breakpoints.

**Comment by hadifawaz1999** [comment]
> > But if someone uses PAA only (no SAX involved), shouldn't the input time series also be znormalized ? I should check the original paper because not sure if its an obligation such as in SAX
> 
> PAA should not depend on the normalization of the data. It was a trick in SAX to be able to have constant breakpoints.

Oh okay, thanks for the info, so yeah will make a SAX obligation only then.

**Comment by hadifawaz1999** [comment]
I remember now, we did add it to SAX, here is the [line](https://github.com/aeon-toolkit/aeon/blob/254758ed57f05066af8df8027ff8050ae937fa91/aeon/transformations/collection/dictionary_based/_sax.py#L119)

**Review by patrickzib — APPROVED** [review]
LGTM

**Pull request merged**
