### PR TITLE
[ENH] Shapelet visualization tools

### LINKED ISSUE #1703: [ENH] Add shapelet visualization method
### Describe the feature or idea you want to propose

Introduce a shapelet visualization tool for part of #1654 

### Describe your proposed solution

Add the visualization methods implemented in `convst` package for RDST, and adapt it to any type of shapelet

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by baraline**
#### Reference Issues/PRs

Fixes #1703 #1684

#### What does this implement/fix? Explain your changes.

Add 3 classes for the following visualisation cases:

- `ShapeletVisualizer` to visualize one shapelet, its values, itself on a time series on best match location, and its distance vector to a time series.
- `ShapeletTransformerVisualizer` takes a fitted shapelet transformer and use `ShapeletVisualizer` methods. The shapelet to visualize is specified by ID when calling one of the three functions.
- `ShapeletClassifierVisualizer` takes a fitted shapelet classifier and use `ShapeletTransformerVisualizer` methods. It adds another method to visualize the best shapelets for a given class. Only linear and forest based classifiers are supported for now.

The structure might be a bit naïve for now and could use some refactoring, but I feel like this belong in a future PR.

For use with `ShapeletTransformClassifier`, the rotation forest need to be switched to another classifier.

While playing with the new visualisation, I wanted to add the option to switch the distance function used to compute the distance vectors, so I added the `distance` parameter (interfacing with the distance module) to `RDST` and  `ShapeletVisualizer` , which uses methods defined in `RDST` to compute distance vectors.

#### Example output :
```python

from aeon.visualisation import ShapeletClassifierVisualizer
from aeon.datasets import load_classification
from aeon.classification.shapelet_based import RDSTClassifier
X, y = load_classification("Beef")
rdst = RDSTClassifier().fit(X, y)
shpt = ShapeletClassifierVisualizer(rdst)
class_id = 1
shpt.visualize_best_shapelets_one_class(X, y, class_id)
```

image

#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### Any other comments?

As MrSEQL and LS have non-standard structure compared to the others, they might not be supported directly in this PR

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [X] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [X] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
awesome stuff, I'll take a look now

**Comment by TonyBagnall** [comment]
not here obvs, but it would be good to standardise the naming etc with internsal shapelets, eg

      """
        if isinstance(self.estimator, (RDSTClassifier, ShapeletTransformClassifier)):
            classifier = self.estimator._estimator
        elif isinstance(self.estimator, (RSASTClassifier, SASTClassifier)):
            classifier = self.estimator._classifier
        else:

**Review by TonyBagnall — CHANGES_REQUESTED** [review]
@baraline maybe Im just looking in the wrong place, but the shapelet notebook seems not to have changed? Is it possible to demo all this in a notebook?

**Comment by baraline** [comment]
Hi Tony, the notebook content didn't change, I just opened it and it seem to have render the image again, leading to à change. 
My goal once the pr is in is to use all this in the shapelet notebook while I update it

**Review by TonyBagnall — APPROVED** [review]
lgtm, thanks for this

**Pull request merged**
