### PR TITLE
[MNT] Allow Python 3.12

### LINKED ISSUE #858: [ENH] Update to support python 3.12
### Describe the feature or idea you want to propose

might be worth testing what breaks if we update to allow python 3.12

### Describe your proposed solution

try it and see what breaks

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
#### Reference Issues/PRs

Resolves #858 

#### What does this implement/fix? Explain your changes.

Raises Python version bound and enables testing for Python 3.12

This includes:
- Removing Python 3.9 and 3.11 from PR testing to save resources
- Adding a Python version bound to `tensorflow` (and friends), `dask` and `mlflow`
- Reworking deep learners and networks to better handle soft dependencies and the `tensorflow` bound change

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Currently waiting on (at least) https://github.com/numba/numba/issues/9197.

**Comment by MatthewMiddlehurst** [comment]
Also, after this I am going to suggest we remove 3.9 and 3.11 from PR testing to save resources. Most of the work going on there is redundant, and any very specific version issues should be picked up on the nightly test,

**Comment by MatthewMiddlehurst** [comment]
Would appreciate a comment on the DL changes @hadifawaz1999

**Comment by hadifawaz1999** [comment]
> Would appreciate a review on the DL changes @hadifawaz1999. None of the actual content of the files should have changed, just how tags inheritance, soft dependencies and superclass init are handled.

just did a check on all deep learning changes, it all looks good to me, thanks @MatthewMiddlehurst

**Review by TonyBagnall — APPROVED** [review]

**Comment by TonyBagnall** [comment]
LGTM

**Pull request merged**
