### PR TITLE
[MNT] Remove `keras` bound

### LINKED ISSUE #1724: [MNT] Lift `keras` version bound
### Describe the issue

We are having CI errors due to the latest `keras` update. See:

broken (3.4.0) https://github.com/aeon-toolkit/aeon/actions/runs/9660623120/job/26646621175
fine (3.3.3) https://github.com/aeon-toolkit/aeon/actions/runs/9652301805/job/26622147143

We want to eventually remove this and fix the underlying issue.

### Suggest a potential alternative/fix

Unknown what it is in the new version that's causing these errors.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
#### Reference Issues/PRs

fixes #1724 

#### What does this implement/fix? Explain your changes.

Removes the version bound on `keras` (if CI passes).

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
so good news keras fixed the loading issue and they are waiting for it to be released in keras 3.4.2 https://github.com/keras-team/keras/issues/19976
first issue that mentioned it: https://github.com/keras-team/keras/issues/19921
first pr that tried to fix it: https://github.com/keras-team/keras/pull/19924
second pr that tried to fix it: https://github.com/keras-team/keras/pull/19927
and now the new release is pr is still open once its in main we can re-run your pr on keras bound

**Comment by hadifawaz1999** [comment]
can we try this now @MatthewMiddlehurst  ?

**Comment by MatthewMiddlehurst** [comment]
feel free to make any changes you want

**Review by hadifawaz1999 — APPROVED** [review]
its working @MatthewMiddlehurst

**Pull request merged**
