### PR TITLE
[MNT] Outdated notebooks and upgraded `ruff` bound

### PR DESCRIPTION
**Pull request by aryanpola**
What does this implement/fix? Explain your changes.
Updated ruff version bound for pre-commit checks to version 0.6.2
Added docstrings for the specified ruff errors.

#1990

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
```
examples/benchmarking/bakeoff_results.ipynb:1:1: This file does not match the schema expected of Jupyter Notebooks: unknown field `outputs`, expected one of `attachments`, `id`, `metadata`, `source` at line 232 column 3
examples/clustering/partitional_clustering.ipynb:1:1: This file does not match the schema expected of Jupyter Notebooks: unknown field `outputs`, expected one of `attachments`, `id`, `metadata`, `source` at line 153 column 3
examples/datasets/provided_data.ipynb:1:1: This file does not match the schema expected of Jupyter Notebooks: unknown field `outputs`, expected one of `attachments`, `id`, `metadata`, `source` at line 248 column 3
```

This is new and odd. May need to re-run the notebooks

**Comment by MatthewMiddlehurst** [comment]
Hi @aryanpola, I fixed the previous failure by rerunning the notebook, but there seems to be a couple of new notebook functions which need comments now. Would you like to fill these out or I can do so?

**Comment by aryanpola** [comment]
> Hi @aryanpola, I fixed the previous failure by rerunning the notebook, but there seems to be a couple of new notebook functions which need comments now. Would you like to fill these out or I can do so?

Hi @MatthewMiddlehurst, I've added comments for the necessary functions.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
@all-contributors add @aryanpola for docs

**Pull request merged**
