### PR TITLE
[MNT] fixed precommit stack level warnings

### PR DESCRIPTION
**Pull request by chrisholder**
#### Reference Issues/PRs
#588 

#### What does this implement/fix? Explain your changes.

When I run precommit locally I get all these warnings:

image

This PR fixes these warnings by adding the stack level argument to all these intances of warnings.warn.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [x] For new estimators, I've added the estimator to the online documentation.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
good stuff, does this fix #588 ?

**Comment by chrisholder** [comment]
Yes I completly forgot i raised that issue ill add it

**Comment by MatthewMiddlehurst** [comment]
I'm interested to see what the visual difference between the different levels is actually. If `stacklevel=2` just looks bad may be worth setting it to 0

**Comment by TonyBagnall** [comment]
> I'm interested to see what the visual difference between the different levels is actually. If `stacklevel=2` just looks bad may be worth setting it to 0

I think it recommends 2, we have set it there elsewhere

**Review by TonyBagnall — APPROVED** [review]
I'm ok with keeping it at stacklevel 2 as we have done before

**Review by MatthewMiddlehurst — APPROVED** [review]
Yes was just interested to see the difference but not urgent, the change is good.

**Pull request merged**
