### PR TITLE
Lazy Importing for Distance_matrix profile

### PR DESCRIPTION
**Pull request by aryanpola**
What does this implement/fix? Explain your changes.
Implementing Lazy loading which imports packages during runtime when called in a specific function in Dictionary-based modules.
#2021

### CODE REVIEW

**Comment by aryanpola** [comment]
@baraline I've implemented lazy loading and pre-commit passes locally but not in github actions.

**Comment by baraline** [comment]
Hi, the original issue is not about dictionnary methods, I'm not sure what was your goal here ?

**Comment by aryanpola** [comment]
> Hi, the original issue is not about dictionnary methods, I'm not sure what was your goal here ?

Ohh! My bad, I think it should be implemented under similarity search.

**Comment by baraline** [comment]
I see where the confusion might have come from, edited the original issue

**Comment by aryanpola** [comment]
I'll create a new PR for this. Deleting this one.

**Pull request closed without merging**
