### PR TITLE
[ENH] Forecasting tests

### PR DESCRIPTION
**Pull request by TonyBagnall**
forecasting test reductions taken from the bad place

### CODE REVIEW

**Comment by TonyBagnall** [comment]
well maybe not!

**Comment by TonyBagnall** [comment]
and of course they fail all tests!

**Comment by MatthewMiddlehurst** [comment]
some of these could still be good potentially?

**Comment by TonyBagnall** [comment]
yes will reopen after the testing overhaul

**Comment by TonyBagnall** [comment]
closing this because its too many confusing things at once

**Pull request closed without merging**
