### PR TITLE
[DOCS] attempt to minimise docstring warnings

### PR DESCRIPTION
**Pull request by TonyBagnall**
adds some spaces and full stops to _base.py in a first attempt to reduce the scale of doctest warnings, which may be failing CI intermittently.

So I had a five hour train journey and little mental capacity to do proper work, so I spent my time correcting docstring errors. Sorry its so big, for any clashes just override changes if you want, they are trivial to do again and there are still a gazillion more to fix anyway, currently 500+ errors let alone warnings. 

I have completely left the notebooks for now until the raft of notebook PRs are in, then I will go through the entire documentation and get it into a passable first version

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Seems to be an issue with the HC1 docstring currently which it does not like

```
Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7f113c7af790> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry 'For the Java version, see' in the docstring of HIVECOTEV1 in /home/docs/checkouts/readthedocs.org/user_builds/aeon-toolkit/envs/572/lib/python3.9/site-packages/aeon/classification/hybrid/_hivecote_v1.py.)
```

**Comment by TonyBagnall** [comment]
yes I was doing this on my old laptop which does not have git/pre-commit installed and no bandwidth to get it.

**Comment by TonyBagnall** [comment]
which was a mistake because it has cocked up all the indenting!

**Review by MatthewMiddlehurst — APPROVED** [review]
Lots of small docstring changes to remove sphinx warnings.

Not gone through each one in full but LGTM,

**Pull request merged**
