### PR TITLE
[ENH] add model checkpoint to inceptionTime deep classifier

### PR DESCRIPTION
**Pull request by hadifawaz1999**
Part of #321 
to see if it works fine, if yes than I should add the removal of the file saved.
Even if the tests get checked, this should get in before the addition of the removal of the saved model using `os.remove`

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
This should be ready now to get in.

**Review by TonyBagnall — DISMISSED** [review]

**Comment by TonyBagnall** [comment]
Have you removed it from excluded list?

**Comment by hadifawaz1999** [comment]
@TonyBagnall which test do we exclude, the `test_save_estimators_to_file` only or the `test_persistence_via_pickle` as well ?

**Review by MatthewMiddlehurst — APPROVED** [review]
We should probably `import time` at the top of the file but I'm not gonna make this rerun CI for that.

**Comment by hadifawaz1999** [comment]
Yeah @MatthewMiddlehurst i can keep it in mind for the next PR that includes deep learning models

**Pull request merged**
