### PR TITLE
[ENH] Add tags for estimators using the taxonomy of classification

### LINKED ISSUE #126: [ENH] classifier_type tags in classifiers
Looking to tidy up note books so we have one for each classifier type. Classifiers have a tag classifier_type to reflect the package they are in. For example, the FreshPrince classifier is in the feature_based package and has this tag
        "classifier_type": "feature"
a quick look indicates these tags are not present in all classifiers, and some may be incorrect. For example, deep_learning do not have tags, and convolution_based should change from kernel to convolution. Currently, the tags for this as follows

(
    "classifier_type",
    "classifier",
    (
        "list",
        [
            "dictionary",
            "distance",
            "feature",
            "hybrid",
            "interval",
            "kernel",
            "shapelet",
        ],
    ),
    "which type the classifier falls under in the taxonomy of time series "
    "classification algorithms.",
so I am going to make the following changes

kernel -> convolution, 
add one for deep learning ("deep_learning"?). sklearn and compose

then I will add in any missing. Just putting this here in case there is some issue I have overlooked with changing tags, it cascades throughout the whole toolikit ....

### PR DESCRIPTION
**Pull request by TonyBagnall**
tidies up estimator tags:
Not introducing list of numpy yet, will need to write a converter to do that.
1. changes classifier_type to algorithm_type in registry/_tags.py, widens scope to regressors and clusterers
    (
        "algorithm_type",
        ["classifier", "early_classifier", "regressor", "clusterer"](
            "list",
            [
                "dictionary",
                "distance",
                "feature",
                "hybrid",
                "interval",
                "convolution",
                "shapelet",
                "deeplearning",
            ],
        ),

2. Changes kernel tag to convolution
3. Adds deeplearning tag
4. Adds missing tags to deep learners
5. Changes all classifier_list to estimator_list usage, checks all classifiers have this tag except for composite

#### Reference Issues/PRs
Fixes #126 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by patrickzib** [comment]
Not sure about clusterer as terminology. Clustering or clustering algorithm would be more common

**Comment by TonyBagnall** [comment]
> Not sure about clusterer as terminology. Clustering or clustering algorithm would be more common

I agree its a bit weird, but went with it for consistency.
classification -> classifier
regression -> regressor
clustering -> clusterer

i.e. a thing that makes clusters.

**Comment by TonyBagnall** [comment]
just realised estimator_type conflates with the attribute  in base class
_estimator_type     : string required by sklearn, set to "classifier"

so need something else to call it. God string naming is annoying because you cant refactor, so have to manually change 20+ files. In Java Id make them enum types, but I'm not sure about enums in python.

**Comment by TonyBagnall** [comment]
> Not sure about clusterer as terminology. Clustering or clustering algorithm would be more common

just saw this on scikit, they call them clusterer, but bottle at calling it ClustererMixin :)

image

**Comment by TonyBagnall** [comment]
how about algorithm_type instead of estimator_type?

**Pull request merged**
