### PR TITLE
[ENH] Testing revision version 1

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs

Dependent on: #595 and #437 

See also:
https://github.com/aeon-toolkit/aeon/issues/418
https://github.com/aeon-toolkit/aeon/issues/59
https://github.com/aeon-toolkit/aeon/issues/151
https://github.com/aeon-toolkit/aeon/issues/154

#### What does this implement/fix? Explain your changes.

This is the version of the new testing model I am proposing. Basically everything switches on MATRIXDESIGN. By day, this boolean is set to True, dramatically reducing CI time. By night, it becomes a monster, and runs full tests on everything, everywhere, all the time.

### CODE REVIEW

**Comment by hadifawaz1999** [comment]
Small question about this, how would the flag be controlled in CI ?

**Comment by TonyBagnall** [comment]
> Small question about this, how would the flag be controlled in CI ?

its a command line flag, used in conftest.py, but @MatthewMiddlehurst knows more

def pytest_configure(config):
    """Pytest configuration preamble."""
    if config.getoption("--matrixdesign") in [True, "True"]:
        test_all_estimators.MATRIXDESIGN = True

**Comment by hadifawaz1999** [comment]
> > Small question about this, how would the flag be controlled in CI ?
> 
> its a command line flag, used in conftest.py, but @MatthewMiddlehurst knows more
> 
> def pytest_configure(config): """Pytest configuration preamble.""" if config.getoption("--matrixdesign") in [True, "True"]: test_all_estimators.MATRIXDESIGN = True

I think its a good idea to use this flag

**Comment by TonyBagnall** [comment]
I dont view this as a permanent solution, but it is very simple and I think may serve us for a while. Its not going into 0.4 though

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
