### PR TITLE
[ENH] Recursive Median Sieve Transformer

### PR DESCRIPTION
**Pull request by Cyril-Meyer**
#### Reference Issues/PRs

Implement Recursive Median Sieve filter asked in #1920.

#### What does this implement/fix? Explain your changes.

Add a new transformation, named `SIVSeriesTransformer` which use [SciPy median_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.median_filter.html)

#### Does your contribution introduce a new dependency? If yes, which one?

No, but we add another SciPy usage.

#### Any other comments?

Code is based on previous work `DFTSeriesTransformer`. I don't think I've forgotten anything, but there may still be references to the DFT as I started by copying _dft.py and test_dft.py.

This PR and #1984 may have conflict for documentation and init (easy to solve).

Name choice came from https://link.springer.com/chapter/10.1007/978-3-030-29859-3_5 (reference in linked issue) but can be changed to something else.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

### CODE REVIEW

**Comment by Cyril-Meyer** [comment]
Here is a visualization of x12r vs fit_transform(x12r) with the tests parameters.

SIV_1
SIV_2
SIV_3
SIV_5
SIV_7
SIV_10
SIV_11
SIV_ 2, 3
SIV_ 3, 5
SIV_ 3, 5, 7
SIV_ 3, 5, 7, 11

**Comment by Cyril-Meyer** [comment]
I. Using list [3, 5, 7] as default instead of "3" is better as its just a median filter if not using list of parameters.

-----

II. Some tests failed ([example](https://github.com/aeon-toolkit/aeon/actions/runs/10442638302/job/28915156413?pr=1985#step:7:266))

Error is due to the `__init__` method that convert int parameter into list of the single int.
But this make problem with `test_set_params_sklearn` which "check that set_params works correctly, mirrors sklearn check_set_params."

Commit 91af2041d49eb05f8d32cb13e3b4d632fdd8514c try to fix this and implement I.
`window_length=None` for default parameter is used because of error if using mutable data for args default.
```
aeon/transformations/series/_siv.py:57:38: B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
```

-----

III. First fix does not work, so proposed a84f10cf0a9065146426b8a447905055f43a3650
The only solution to me about for now is to move the `window_length` conversion into `_transform`.
Feedbacks are very welcome as I'm not sure this solution is clean enough.

**Review by TonyBagnall — APPROVED** [review]
I did not know this was in scipy, Andrew Bangham would have been happy, he was very proud  of that paper. Last time I used it was with a horrible C implementation

**Comment by TonyBagnall** [comment]
minor conflict to resolve @Cyril-Meyer

**Comment by Cyril-Meyer** [comment]
> minor conflict to resolve @Cyril-Meyer

I resolved it directly on GitHub so we need to check that doc is good for both SG and SIV as the commit looks a little strange.

**Comment by Cyril-Meyer** [comment]
`FAILED aeon/similarity_search/distance_profiles/tests/test_naive_distance.py::test_naive_distance_unequal_length[euclidean-float64] - ReferenceError: underlying object has vanished
`
I don't really know how it is related, but test failed...

**Comment by TonyBagnall** [comment]
ah no, thats not related

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
