### PR TITLE
[ENH] Enhancing `BaseCollectionTransformers`+Tidying `Utils` dir

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
Fixes : #1172 
added `"fit_is_empty": True` to
* ar_coeffient.py
* periodogram.py
* TimeSeriesScaler

Part of : #1094 
- renamed `stats.py` from aeon/utils

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Like #1266, any public `stats.py` methods will need to be deprecated first.

**Comment by MatthewMiddlehurst** [comment]
Are there any other transformers which do not have `_fit` but are missing the tag? We should check before closing #1172.

**Comment by AnonymousCodes911** [comment]
> Like #1266, any public `stats.py` methods will need to be deprecated first.

should it be done in a separate PR or should I try implementing it here only?

**Comment by AnonymousCodes911** [comment]
> Are there any other transformers which do not have `_fit` but are missing the tag? We should check before closing #1172.

@MatthewMiddlehurst, I think now it covers the entire `aeon/transformations`, please review.

**Comment by AnonymousCodes911** [comment]
In `subset.py`>`IndexSubset` we have the  ` "remember_data": True,` tag so according to the tests it should have the `"fit_is_empty":False`, but currently _fit is not implemented in it, so should we use something like?

```python
_fit(self, X, y=None):   
    self._X = X.copy()    
    return self
```

**Comment by MatthewMiddlehurst** [comment]
You can undo the change to `aeon/utils/stats.py`, the deprecation only applies to public methods.

Please isolate the changes to `collections/` for now and don't edit the transformer base class. You do not need to add the tag if it matches the default `"fit_is_empty": False,`.

**Comment by AnonymousCodes911** [comment]
@MatthewMiddlehurst are the changes in line with the requirements?

**Review by TonyBagnall — APPROVED** [review]
This all looks good to me, thanks

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
