### PR TITLE
added plot visualizing the Italy power data

### PR DESCRIPTION
**Pull request by kgmuzungu**
Hi, 

I havnt said hello yet in the Slack channel, but will do. I have been on the PyData Amsterdam. I am really enthusiastic about your project! 

Reading through https://www.aeon-toolkit.org/en/latest/examples/classification/distance_based.html I found the Italy power consumption dataset not intuitive. Therefor my suggestion to add a little description plus the plots. 

Also and maybe I should not have done this. I allowed all test data and not just the first 10 rows of the test data. The classification is fast enough! Hence I have deleted two rows 
`X_test = X_test[:10]
y_test = y_test[:10]`

Maybe you like it. 
All the best, 
Klaus 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [ ] For new estimators, I've added the estimator to the online documentation.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hello @kgmuzungu thanks for the contribution! Matt and I are away at conference this week, so may be a bit slow to look at this, but I think the fail is not from your code

**Comment by TonyBagnall** [comment]
bug independent of this pr for the examples fails, see #747

but its also failing the style test, have you installed pre-commit? Its really helpful for picking these up

**Comment by TonyBagnall** [comment]
@kgmuzungu could you update this from main? The notebook bug has been fixed

**Comment by kgmuzungu** [comment]
I will have a look at it!

**Comment by kgmuzungu** [comment]
there were two imports missing in the plotting part. I fixed that. pre-commit had no complains.

**Comment by TonyBagnall** [comment]
looks great, thanks very much for this

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
