### PR TITLE
[ENH] Documented why rotational forest isn't visualisable in the shapelet viz module

### LINKED ISSUE #2007: [DOC] ShapeletClassifierVisualizer doesn't support STC default estimator
### Describe the bug

Currently unable to visualise STC using the default rotational forest estimator.

### Steps/Code to reproduce the bug

rst_rf = ShapeletTransformClassifier(
    max_shapelets=10,
    random_state=99,  # Same random state as for the individual transform from above
).fit(X_gun_train, y_gun_train)
rst_rf_vis = ShapeletClassifierVisualizer(rst_rf)

### Expected results

No error.

### Actual results

NotImplementedError: The classifier linked to the estimator is not supported. We expect a classifier inheriting from LinearClassifierMixin, BaseForest or BaseDecisionTree but got <class 'aeon.classification.sklearn._rotation_forest_classifier.RotationForestClassifier'>

### Versions

_No response_

### PR DESCRIPTION
**Pull request by IRKnyazev**
#### Reference Issues/PRs
Fixes #2007 

#### What does this implement/fix? Explain your changes.
Added an explanation as to why the shapeletclassifiervizualiser doesn't support certain classifiers, specifically the rotational forest.

added the following md section to the shapelet_based notebook: 
Similarly to visualizing transformers, we can also visualize individual shapelets of a shapelet-based classifier, and, when possible, plot the best shapelets based on feature importance criterions of some estimators. The scope of these estimators is generally limited to those inheriting from scikit-learn’s BaseDecisionTree, BaseForest, or LinearClassifierMixin classes, as these are known to be among the most interpretable models where feature weights directly relate to the input features.

For instance, in aeon's Rotational Forest, the application of Principal Component Analysis (PCA) complicates tracing feature importance back to individual shapelets. Since PCA transforms the original feature space into a new set of uncorrelated components, it becomes difficult to directly associate these components with the original shapelet features, reducing the interpretability in terms of feature importance.

### CODE REVIEW

**Comment by IRKnyazev** [comment]
@baraline Hey, this is something we discussed in Slack a while back. When you have a free moment could you look over my explanation?

**Review by TonyBagnall — APPROVED** [review]

**Comment by TonyBagnall** [comment]
@all-contributors and @IRKnyazev for docs

**Comment by TonyBagnall** [comment]
https://github.com/all-contributors and @IRKnyazev for doc

**Comment by MatthewMiddlehurst** [comment]
@all-contributors add @IRKnyazev for docs

**Pull request merged**
